import type { AIDifficulty } from '../types/player';
import type { GameMetadata } from '../types/game';

/**
 * Canonical game metadata, shared by the client and the server.
 *
 * Keeping this in `shared` guarantees the browser, the REST catalogue, the
 * lobby rules panel and the server registry can never drift apart.
 */

export const REACTION_RACE_METADATA = {
  id: 'reaction-race',
  name: 'Reaction Race',
  description:
    'Wait for the signal, then tap first. Tap too early and you false start. Best of five rounds wins.',
  category: 'reflex' as const,
  icon: '⚡',
  thumbnail: '⚡',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 90,
  difficulty: 'easy' as const,
  controls: 'Tap / click / press Space as fast as you can after the GO signal.',
  rules: [
    'Each round the server waits a random 1.5–5 seconds before showing GO.',
    'Tapping before GO is a false start: you score nothing this round.',
    'The first valid reaction wins the round.',
    'Reactions faster than 150ms are impossible and are rejected as false starts.',
    'Best of 5 rounds — the player with the most round wins takes the match.',
  ],
  scoring: '1 point per round won. Ties are broken by average reaction time.',
  winCondition: 'Win the most of five rounds.',
  tags: ['reflex', 'fast', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  version: '1.0.0',
} satisfies GameMetadata;


export const MEMORY_MATCH_METADATA = {
  id: 'memory-match',
  name: 'Memory Match',
  description:
    'Flip two cards, remember what you saw and collect the most pairs. The full layout never leaves the server.',
  category: 'memory' as const,
  icon: '🧠',
  thumbnail: '🧠',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'medium' as const,
  controls: 'Tap a card to flip it. Match a pair to keep your turn.',
  rules: [
    'Players take turns flipping two cards.',
    'A matching pair scores 1 point and the player continues.',
    'A mismatch flips both cards back and the turn passes on.',
    'The player with the most pairs when the board is clear wins.',
    'Only revealed cards are ever sent to clients — the hidden layout stays on the server.',
  ],
  scoring: '1 point per pair collected.',
  winCondition: 'Collect the most pairs.',
  tags: ['memory', 'turn-based', 'family', '2-4 players'],
  featured: true,
  gridOptions: ['4x4', '6x4', '6x6'],
  version: '1.0.0',
} satisfies GameMetadata;


export const WORD_RACE_METADATA = {
  id: 'word-race',
  name: 'Word Race',
  description:
    'Name as many valid words as you can in the given category before the clock runs out. The server owns the dictionary.',
  category: 'word' as const,
  icon: '🔤',
  thumbnail: '🔤',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Type a word that fits the category and press Enter.',
  rules: [
    'Each round gives a category and 60 seconds.',
    'A valid, unused word scores 1 point.',
    'Invalid or repeated words score nothing.',
    'Only the server dictionary decides what is valid — clients cannot invent words.',
    'Best of 3 rounds wins.',
  ],
  scoring: '1 point per unique valid word. Highest total after 3 rounds wins.',
  winCondition: 'Score the most valid words across three rounds.',
  tags: ['word', 'typing', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 3,
  version: '1.0.0',
} satisfies GameMetadata;


export const DOTS_AND_BOXES_METADATA = {
  id: 'dots-and-boxes',
  name: 'Dots and Boxes',
  description:
    'Draw lines, complete boxes and chain your way to victory. Completing a box earns another turn.',
  category: 'strategy' as const,
  icon: '🔲',
  thumbnail: '🔲',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 300,
  difficulty: 'medium' as const,
  controls: 'Tap the gap between two dots to draw a horizontal or vertical line.',
  rules: [
    'Players take turns drawing one horizontal or vertical line.',
    'Completing the fourth side of a box scores 1 point and earns another turn.',
    'The board is finished when every box is claimed.',
    'The player with the most boxes wins.',
  ],
  scoring: '1 point per completed box.',
  winCondition: 'Own the most boxes when the grid is full.',
  tags: ['strategy', 'turn-based', 'classic', '2-4 players'],
  featured: false,
  gridOptions: ['4x4', '6x6', '8x8'],
  version: '1.0.0',
} satisfies GameMetadata;


export const MATH_RUSH_METADATA = {
  id: 'math-rush',
  name: 'Math Rush',
  description:
    'Solve arithmetic challenges against the clock. Faster correct answers score more. The server owns every question and answer.',
  category: 'math' as const,
  icon: '🧮',
  thumbnail: '🧮',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Type your answer and press Enter (or use the on-screen keypad).',
  rules: [
    'Everyone gets the same question at the same time.',
    'A correct answer scores 10 points plus a speed bonus of up to 10.',
    'A wrong answer scores nothing and locks you out of that question.',
    'Unanswered questions score nothing when the timer runs out.',
    'Highest score after the final question wins.',
  ],
  scoring: '10 points per correct answer + up to 10 bonus points for speed.',
  winCondition: 'Score the most points across all questions.',
  tags: ['math', 'speed', 'skill', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const BATTLE_2048_METADATA = {
  id: '2048-battle',
  name: '2048 Battle',
  description:
    'Two private 2048 boards, one clock. Slide, merge and outscore your rival — the server owns every tile.',
  category: 'strategy' as const,
  icon: '🔢',
  thumbnail: '🔢',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 200,
  difficulty: 'medium' as const,
  controls: 'Arrow keys, swipe on your board or use the on-screen D-pad. Both players play at the same time.',
  rules: [
    'Each player gets their own private 4x4 board playing standard 2048.',
    'Swipe or press a direction: every tile slides and equal neighbours merge once per move.',
    'Every valid move spawns a new tile (a 2, occasionally a 4) on your board.',
    'Merging tiles adds their combined value to your score.',
    'When a board has no legal moves left it locks — that player stays in the match and waits.',
    'The match ends when both boards lock or the clock runs out; the higher score wins.',
  ],
  scoring: 'Merges add their value to your score. Higher total wins; equal totals are a draw.',
  winCondition: 'Finish with a higher score than your rival.',
  tags: ['strategy', 'puzzle', 'numbers', '2 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const MAZE_RACE_METADATA = {
  id: 'maze-race-2d',
  name: 'Maze Race 2D',
  description:
    'A maze generated fresh from the server seed — everyone races from their own start to the flag. Walls are real: only the server moves you.',
  category: 'reflex' as const,
  icon: '🧩',
  thumbnail: '🧩',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'Arrow keys, swipe or the on-screen D-pad to move one cell at a time.',
  rules: [
    'The maze is generated deterministically from the server seed — identical for everyone in the match.',
    'Every player starts from their own start cell, the same distance from the goal.',
    'Move up, down, left or right — one cell per move, walls block you.',
    'The first player to reach the flag wins rank 1; later finishers take the next ranks.',
    'Players who never reach the goal before the timeout are ranked below every finisher (closer to the goal ranks higher).',
  ],
  scoring: 'Faster finishers score more (remaining time bonus). Unfinished players score 0.',
  winCondition: 'Reach the goal first.',
  tags: ['reflex', 'maze', 'race', '2-4 players'],
  featured: false,
  gridOptions: ['11x11', '15x15', '19x19'],
  version: '1.0.0',
} satisfies GameMetadata;


export const WORD_SCRAMBLE_METADATA = {
  id: 'word-scramble-battle',
  name: 'Word Scramble Battle',
  description:
    'Unscramble the shuffled letters faster than everyone else. The original word never leaves the server until the round ends.',
  category: 'word' as const,
  icon: '🔤',
  thumbnail: '🔀',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Type what you think is the hidden word and press Enter.',
  rules: [
    'Each round the server picks a word and shuffles its letters for everyone.',
    'Type the original word and submit — first correct answer scores.',
    'Correct answers earn 1 point, plus 1 bonus point for solving in the first half of the round.',
    'Wrong answers score nothing and you can simply try again.',
    'A round ends when every active player has solved it, or when its timer runs out.',
    'The original word is revealed between rounds; after the final round the highest score wins.',
  ],
  scoring: '1 point per solved word + 1 speed bonus for early solves. Equal totals are a draw.',
  winCondition: 'Solve more words than your rivals across all rounds.',
  tags: ['word', 'typing', 'puzzle', '2-4 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 5,
  version: '1.0.0',
} satisfies GameMetadata;


export const SHAPE_MATCH_METADATA = {
  id: 'shape-match-battle',
  name: 'Shape Match Battle',
  description:
    'Spot the shape that matches the target — fast, sharp eyes win. The correct option is decided by the server alone.',
  category: 'reflex' as const,
  icon: '🔶',
  thumbnail: '🔶',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 130,
  difficulty: 'easy' as const,
  controls: 'Tap the option that matches the target shape.',
  rules: [
    'Every round shows one target shape and four options — exactly one matches.',
    'Tap an option: a correct match scores 1 point, plus 1 bonus point in the first half of the round.',
    'A wrong option scores nothing — you only get one pick per round.',
    'The round ends when every active player has picked, or when its timer runs out.',
    'After the final round the highest score wins; equal scores are a draw.',
  ],
  scoring: '1 point per correct match + 1 speed bonus for fast picks.',
  winCondition: 'Match more shapes than your rivals.',
  tags: ['reflex', 'pattern', 'speed', '2-4 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 10,
  version: '1.0.0',
} satisfies GameMetadata;


export const SNAKE_BATTLE_METADATA = {
  id: 'snake-battle',
  name: 'Snake Battle',
  description:
    'Two snakes, one arena. Grab the food, cut off your rival and be the last serpent sliding. The server moves every snake on a fixed clock.',
  category: 'reflex' as const,
  icon: '🐍',
  thumbnail: '🐍',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Steer with WASD / arrow keys, swipe on the arena or use the D-pad below it.',
  rules: [
    'Both snakes slide on the same 17x17 grid, one cell every quarter second.',
    'Turn up, down, left or right — reversing into yourself is rejected by the server.',
    'Eating food grows your snake by one segment and scores 10 points.',
    'Hitting a wall, any snake body or another head kills your snake instantly.',
    'A dead snake is out, but the survivor keeps eating until the clock or their own crash.',
    'Survive longer to win; if both die on the same step the higher score takes it.',
  ],
  scoring: '10 points per food. Survival beats score; score breaks survival ties.',
  winCondition: 'Outlive your rival (or outhunt them on the fatal step).',
  tags: ['reflex', 'arcade', 'classic', '2 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const TARGET_RUSH_METADATA = {
  id: 'target-rush',
  name: 'Target Rush',
  description:
    'Three targets, one symbol to hit. Read the prompt, tap the right target first and build a streak your rival cannot match.',
  category: 'reflex' as const,
  icon: '🎯',
  thumbnail: '🎯',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 120,
  difficulty: 'easy' as const,
  controls: 'Tap or click the target that matches the prompt symbol.',
  rules: [
    'Every round shows a prompt symbol and three large targets — exactly one matches.',
    'The first correct tap scores: 10 points, up to 10 extra for speed, plus a combo bonus for your streak.',
    'Tapping a wrong target scores nothing, breaks your streak and locks you out for a second.',
    'A round ends on the first correct tap or when its timer runs out (all streaks reset).',
    'Eight rounds — the highest total score wins, equal totals are a draw.',
  ],
  scoring: '10 points per hit + up to 10 speed points + 2 per streak step (max +6).',
  winCondition: 'Score the most points across eight rounds.',
  tags: ['reflex', 'speed', 'focus', '2 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 8,
  version: '1.0.0',
} satisfies GameMetadata;


export const PADDLE_DUEL_METADATA = {
  id: 'paddle-duel',
  name: 'Paddle Duel',
  description:
    'Classic paddle versus paddle. Keep the ball in play, angle your returns and outlast your rival — first to the point limit takes the duel.',
  category: 'reflex' as const,
  icon: '🏓',
  thumbnail: '🏓',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Slide your paddle with W/S, the up/down arrow keys, or drag on your side of the arena.',
  rules: [
    'Both paddles live on the server — the ball is simulated there on a fixed clock.',
    'The ball bounces off the top and bottom walls; returning it speeds it up a little.',
    'Hit the ball with the edge of your paddle to angle it sharply.',
    'If the ball passes your paddle your rival scores a point.',
    'First to 7 points (configurable 3–15) wins; at the 3-minute timeout the leader takes it.',
  ],
  scoring: '1 point per rally won by your opponent missing the ball.',
  winCondition: 'Reach the point limit first, or lead when the clock ends.',
  tags: ['reflex', 'arcade', 'classic', '2 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 7,
  version: '1.0.0',
} satisfies GameMetadata;


export const BRICK_BREAKER_METADATA = {
  id: 'brick-breaker-battle',
  name: 'Brick Breaker Battle',
  description:
    'Two identical arenas, one mirrored brick wall each. Break your wall faster, chain combos and bank more points than your rival before the clock or your lives run out.',
  category: 'reflex' as const,
  icon: '🧱',
  thumbnail: '🧱',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Slide your paddle with A/D, the left/right arrow keys, mouse or by dragging on your arena.',
  rules: [
    'Each player breaks their own identical wall — the server simulates both balls.',
    'Bricks are worth more the higher they sit: 10 to 30 points.',
    'Chain bricks without touching your paddle to multiply them, up to x4.',
    'Missing the ball costs a life; you have three, then your run is over.',
    'Clearing the whole wall banks a 100-point bonus — most points in 3 minutes wins.',
  ],
  scoring: 'Brick points x combo multiplier (up to x4) + 100 for a full clear.',
  winCondition: 'Score the most points (ties: earlier finish, then lives left).',
  tags: ['reflex', 'arcade', 'classic', '2 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const PATTERN_MEMORY_METADATA = {
  id: 'pattern-memory-battle',
  name: 'Pattern Memory Battle',
  description:
    'Watch the tiles flash, then replay the sequence from memory. The patterns grow longer every round — who can keep up longest?',
  category: 'memory' as const,
  icon: '🔮',
  thumbnail: '🔮',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Watch the flashes, then tap the tiles in the same order.',
  rules: [
    'Both players memorise the exact same server-generated sequence.',
    'The pattern starts at three tiles and grows by one every two rounds.',
    'Replay it in order: every correct tap advances you, one wrong tap ends your attempt.',
    'A full replay scores pattern length x 10, a speed bonus and a streak bonus.',
    'Eight rounds — the highest total wins, equal totals are a draw.',
  ],
  scoring: '10 per tile + up to 5 per tile for speed + a streak bonus (max +6).',
  winCondition: 'Score the most points across eight rounds.',
  tags: ['memory', 'focus', 'party', '2 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 8,
  version: '1.0.0',
} satisfies GameMetadata;


export const DRAW_GUESS_METADATA = {
  id: 'draw-guess-battle',
  name: 'Draw & Guess Battle',
  description:
    'Take turns as the drawer. Sketch a secret word on a 2D canvas while everyone else races to guess it. The word never leaves the server.',
  category: 'word' as const,
  icon: '🎨',
  thumbnail: '🎨',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'easy' as const,
  controls: 'Draw with your finger or mouse. Type guesses and press Enter. Brush, eraser and a simple palette.',
  rules: [
    'Each round one player is the drawer and receives a secret word nobody else can see.',
    'The drawer sketches on a shared 2D canvas; strokes are sent as points, never a screenshot.',
    'Everyone else types guesses. The first correct guess scores the most; later solvers score less.',
    'The drawer earns a bonus for every unique solver.',
    'A round ends when every guesser has solved it, or when the timer runs out.',
    'After several rounds the highest score wins.',
  ],
  scoring: 'First guess 100, then 75 / 50 / 25. Drawer +40 per unique solver.',
  winCondition: 'Score the most points across all drawing rounds.',
  tags: ['word', 'party', 'drawing', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 6,
  version: '1.0.0',
} satisfies GameMetadata;


export const SECRET_ROLE_METADATA = {
  id: 'secret-role',
  name: 'Secret Role',
  description:
    'A family-friendly deduction game. Most players share a secret location — one Secret Agent does not. Clue, vote, and catch the agent (or blend in).',
  category: 'strategy' as const,
  icon: '🕵️',
  thumbnail: '🕵️',
  minPlayers: 3,
  maxPlayers: 4,
  supportedPlayerCounts: [3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 300,
  difficulty: 'medium' as const,
  controls: 'On your turn type a short clue. Then vote for who you think is the Secret Agent. The agent may guess the location.',
  rules: [
    'Each round the server assigns one Secret Agent; everyone else is a Citizen who knows the location.',
    'Roles are private: you only ever see your own role and (if you are a Citizen) the location.',
    'Players take turns giving a short clue about the location without naming it.',
    'After clues, everyone votes for one other player. Majority on the agent → Citizens win the round.',
    'The Secret Agent may guess the location. A correct guess wins the round for the agent.',
    'If the agent is not voted out, the agent wins the round.',
  ],
  scoring: 'Citizen correct vote +100. Agent survives +150. Agent guesses the location +200.',
  winCondition: 'Highest cumulative score after all rounds.',
  tags: ['strategy', 'party', 'deduction', '3-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 4,
  version: '1.0.0',
} satisfies GameMetadata;


export const COLOR_CLASH_METADATA = {
  id: 'color-clash',
  name: 'Color Clash',
  description:
    'Fast colour-selection rounds with a twist: sometimes tap the named colour, sometimes the ink, sometimes the colour you just saw. Labels keep it accessible.',
  category: 'reflex' as const,
  icon: '🌈',
  thumbnail: '🌈',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Tap the colour that matches the instruction. Buttons are large, labelled, and colour-coded.',
  rules: [
    'Each round the server picks a challenge type and the correct colour — clients never decide.',
    'Name: tap the colour that is named. Stroop: tap the ink colour, not the written word.',
    'Memory: a colour flashes, then you pick it from the options. Race: one tile is the target.',
    'The fastest correct tap scores the most; later correct taps score less. A wrong tap scores 0.',
    'One pick per round. After 12 rounds the highest score wins.',
  ],
  scoring: 'Fastest correct 100, then 75 / 50 / 25. Wrong answers score 0.',
  winCondition: 'Score the most points across twelve rounds.',
  tags: ['reflex', 'colour', 'speed', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 12,
  version: '1.0.0',
} satisfies GameMetadata;


export const TERRITORY_RUSH_METADATA = {
  id: 'territory-rush',
  name: 'Territory Rush',
  description:
    'Claim the map. Leave your home, loop a trail and close it to paint the enclosed cells. Cut a rival trail to send them home. Largest territory when the clock ends wins.',
  category: 'reflex' as const,
  icon: '🗺️',
  thumbnail: '🗺️',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Steer with WASD / arrows, swipe or the D-pad. The server moves everyone on its clock.',
  rules: [
    'Everyone starts with a small home territory. You are safe on your own colour.',
    'Leaving home lays a trail. Close a loop back to your land to capture the enclosed cells.',
    'Your trail is vulnerable: a rival stepping on it sends you home. Hitting your own trail does the same.',
    'You cannot leave the map. Homes cannot be stolen.',
    'When the clock ends, the largest territory wins.',
  ],
  scoring: '1 point per owned cell. Ties broken by successful captures, then fewer deaths.',
  winCondition: 'Own the most cells when the timer ends.',
  tags: ['reflex', 'territory', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const COIN_HUNTERS_METADATA = {
  id: 'coin-hunters-arena',
  name: 'Coin Hunters Arena',
  description:
    'Dash around a shared arena vacuuming coins. Gold and rare coins pay more, multipliers and bonus zones juice the haul, and a roaming blocker keeps you honest.',
  category: 'reflex' as const,
  icon: '🪙',
  thumbnail: '🪙',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Move with WASD / arrows, swipe or the D-pad. Collection is confirmed by the server.',
  rules: [
    'The server spawns coins: normal +10, gold +25, rare +50, multiplier 2× for a few seconds.',
    'Stand on a coin (or send collect) — distance and identity are checked server-side.',
    'A 2× bonus zone doubles collections while you stand in it. Slow tiles double your step time.',
    'A moving blocker occupies a cell; walking into it bounces you back.',
    'Duplicate collects award nothing. Highest score when the timer ends wins.',
  ],
  scoring: 'Coin value × active multiplier (personal 2× and/or bonus zone 2×).',
  winCondition: 'Hold the highest score when the arena clock ends.',
  tags: ['reflex', 'arcade', 'collection', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const SHOP_RUSH_METADATA = {
  id: 'shop-rush-battle',
  name: 'Shop Rush Battle',
  description:
    'Race the aisles with a private shopping list. Grab the right items, dump bonus candy and check out before the clock.',
  category: 'strategy' as const,
  icon: '🛒',
  thumbnail: '🛒',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Move with WASD / arrows / swipe / D-pad. Pick up on a shelf, check out on the till.',
  rules: [
    'Each shopper gets a private 3-item list. Inventory holds at most 3 items.',
    'Stand on a shelf and pick to collect. Only the server grants the item.',
    'Bonus candy is never on the list but pays extra at checkout.',
    'Checkout scores matching list items and candy, then deals a fresh list. Wrong items stay in the basket.',
    'Highest checkout score when time ends wins. Lists of other players never leave the server.',
  ],
  scoring: '+40 per listed item, +25 candy, +50 list-complete bonus.',
  winCondition: 'Hold the highest checkout score when the shop closes.',
  tags: ['strategy', 'collection', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const FAKE_DOOR_METADATA = {
  id: 'fake-door-battle',
  name: 'Fake Door Battle',
  description:
    'Four doors, one safe route. Read the clue, remember last round, and skip the fakes — the server owns the answer.',
  category: 'memory' as const,
  icon: '🚪',
  thumbnail: '🚪',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Tap a door (or keys 1–4). Clues are colour, symbol, number, position or memory.',
  rules: [
    'Each round shows four doors and one learnable clue. Exactly one door is safe.',
    'A correct pick advances you. A fake door costs time and scores nothing.',
    'Clues are never random: colour match, unique symbol, even number, far-right, or last-round memory.',
    'The correct door never leaves the server until the reveal.',
  ],
  scoring: 'Correct door +100 plus a speed bonus. Highest total after five rounds wins.',
  winCondition: 'Score the most points across five rounds.',
  tags: ['memory', 'puzzle', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  version: '1.0.0',
} satisfies GameMetadata;


export const MAGNET_THIEF_METADATA = {
  id: 'magnet-thief',
  name: 'Magnet Thief',
  description:
    'Vacuum coins with a directional magnet, then steal a rival gem if you are in range. Ownership is server-side.',
  category: 'strategy' as const,
  icon: '🧲',
  thumbnail: '💎',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Move with WASD / arrows / D-pad. Magnet with Q/E or the magnet buttons (direction + activate).',
  rules: [
    'Step onto a coin to collect it. The server grants the points.',
    'Activate your magnet in a direction to pull nearby coins one cell toward you (cooldown applies).',
    'A carried gem can be stolen if you magnetise within range and the owner is not in a safe corner.',
    'Magnetic zones double range. Clients cannot assign themselves an object.',
  ],
  scoring: 'Coin +10, gem +50 (held at the buzzer). Highest valid total wins.',
  winCondition: 'Hold the highest score when the arena clock ends.',
  tags: ['strategy', 'collection', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const CHAIN_REACTION_METADATA = {
  id: 'chain-reaction-battle',
  name: 'Chain Reaction Battle',
  description:
    'Trigger one node and watch the board cascade. Long, high-value chains win — the server owns every spark.',
  category: 'strategy' as const,
  icon: '💥',
  thumbnail: '💥',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Tap a node to trigger it. Two triggers per round.',
  rules: [
    'Each round the server deals a coloured board of normal, bonus, multiplier, blocker and arrow nodes.',
    'Trigger a node: same-colour neighbours chain. Arrows continue in their direction. Blockers never chain.',
    'You get two triggers per round. Clients submit a node id — never a chain length.',
    'Highest total after four rounds wins.',
  ],
  scoring: 'Chain length × 10 × multipliers, plus 15 per bonus node in the chain.',
  winCondition: 'Score the most points across four rounds.',
  tags: ['strategy', 'puzzle', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 4,
  version: '1.0.0',
} satisfies GameMetadata;


export const ONE_BUTTON_METADATA = {
  id: 'one-button-battle',
  name: 'One Button Battle',
  description:
    'One button, many contexts. Jump, dash, dodge, switch, collect or shield — only if you press in the window.',
  category: 'reflex' as const,
  icon: '🔘',
  thumbnail: '🔘',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 120,
  difficulty: 'medium' as const,
  controls: 'One large action button, or Space. Timing is everything.',
  rules: [
    'A sequence of events approaches. The current context (jump, dash, dodge, switch, collect, shield) is shown.',
    'Press in the timing window to succeed. Early or late presses miss and break your streak.',
    'The server owns the window, the context and the score. Clients only send tap.',
    'Highest score after the sequence wins.',
  ],
  scoring: 'Hit +20 plus 5 per streak step. Misses score 0 and reset the streak.',
  winCondition: 'Score the most points across the event sequence.',
  tags: ['reflex', 'timing', 'party', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const SPLIT_WORLD_METADATA = {
  id: 'split-world',
  name: 'Split World',
  description:
    'See different versions of the same world. Share clues, work together, and find the way out.',
  category: 'strategy' as const,
  icon: '🌍',
  thumbnail: '🌍',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 260,
  difficulty: 'hard' as const,
  controls: 'WASD / arrows / swipe / D-pad. Chat is part of the puzzle.',
  rules: [
    'Five rounds, five arenas: a gate, a key vault, a switch order, pressure plates and an extraction.',
    'The true layout lives on the server. Each seat gets a different lens on the same world.',
    'Wardens see switches and the exit, Gatekeepers see hazards and the gate, Scouts see keys and traps.',
    'Decoy tiles look real to some lenses but are plain floor — only chat separates truth from bait.',
    'Real walls and closed gates block everyone. Hidden tiles and secret orders never leave the server.',
  ],
  scoring:
    'Switch +30, key +25, plate +20, exit +100 plus a speed bonus, round win +25. Hazards and wrong order cost points.',
  winCondition: 'Hold the highest total score after five rounds (rounds won breaks a tie).',
  tags: ['strategy', 'coop', 'puzzle', 'communication', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  version: '2.0.0',
} satisfies GameMetadata;


export const LUDO_METADATA = {
  id: 'ludo',
  name: 'Ludo',
  description:
    'The classic board race. Roll the dice, bring all four tokens home and knock your rivals back to the start.',
  category: 'strategy' as const,
  icon: '🎲',
  thumbnail: '🎲',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 420,
  difficulty: 'easy' as const,
  controls: 'Tap the dice to roll, then tap a highlighted token to move it.',
  rules: [
    'Every player has four tokens. Roll a six to bring one out of the yard.',
    'The server rolls the dice — the result is never decided on your device.',
    'Landing on a lone enemy token sends it back to its yard. Safe squares and pairs are protected.',
    'A six, a capture or bringing a token home earns you another roll. Three sixes in a row forfeits the turn.',
    'You need the exact roll to enter the final home cell. First to bring every token home wins.',
  ],
  scoring: 'Capture +50, token home +100, finishing bonus up to +150, plus a point per cell advanced.',
  winCondition: 'Be the first to bring all your tokens home.',
  tags: ['board', 'classic', 'turn-based', 'family', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const ARROW_PUZZLE_METADATA = {
  id: 'arrow-puzzle',
  name: 'Arrow Puzzle',
  description:
    'Everyone gets the same board of arrows. Fire the ones with a clear path, unlock the rest and clear it first.',
  category: 'strategy' as const,
  icon: '➡️',
  thumbnail: '➡️',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'medium' as const,
  controls: 'Tap or click an arrow to fire it. Highlighted arrows have a clear path.',
  rules: [
    'An arrow can only be fired when every cell between it and the board edge is empty.',
    'Firing an arrow removes it, which opens the path for the arrows behind it.',
    'Every player races on an identical board — the server generates it and guarantees it is solvable.',
    'Firing a blocked arrow costs points, so look before you tap.',
    'Boards get bigger and denser each round: easy, medium, then hard.',
  ],
  scoring: 'Arrow cleared +10, board solved +200, placement and speed bonuses, blocked tap −5.',
  winCondition: 'Hold the highest score after the final round (fastest solve breaks a tie).',
  tags: ['puzzle', 'logic', 'race', 'brain', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 3,
  version: '1.0.0',
} satisfies GameMetadata;


export const BLACK_BLAST_METADATA = {
  id: 'black-blast',
  name: 'Black Blast',
  description:
    'Drop black energy pulses in an abstract arena, catch the rich nodes and set off huge chain reactions.',
  category: 'reflex' as const,
  icon: '⚫',
  thumbnail: '⚫',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / D-pad to move. Tap the pulse button or press Space to drop energy.',
  rules: [
    'Move your marker and drop a pulse. It charges briefly, then expands into a circular zone.',
    'Every energy node caught in the zone is collected and scores points.',
    'Rich nodes detonate too, chaining into new pulses — deep chains multiply your score.',
    'Land pulses back to back to build a combo multiplier up to 4x. A pulse that hits nothing resets it.',
    'Nodes respawn, so the arena never runs dry. Highest score when the clock ends wins.',
  ],
  scoring: 'Energy +20, rich node +60, chain depth bonus per hit, combo multiplier up to 4x.',
  winCondition: 'Hold the highest score when the three minute clock expires.',
  tags: ['arcade', 'reflex', 'chain-reaction', 'combo', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const COUPLE_SYNC_METADATA = {
  id: 'couple-sync',
  name: 'Couple Sync',
  description:
    'Ten short coordination rounds: tap together, relay a secret code, agree on a symbol, act in order and react on cue.',
  category: 'coop' as const,
  icon: '🤝',
  thumbnail: '🤝',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 300,
  difficulty: 'medium' as const,
  controls: 'Tap the action button, pick a symbol, or type the relayed code.',
  rules: [
    'Ten rounds that rotate through five different coordination challenges.',
    'Together: both partners must tap inside a shrinking time window.',
    'Relay: only one of you can see a code — read it out so the other can type it.',
    'Match: both partners must independently choose the same symbol.',
    'Order: act in the exact sequence the server asks for. Signal: react only after the go cue.',
  ],
  scoring: 'Round won +100, streak bonus +25 each, plus a speed bonus. A failed round costs 20.',
  winCondition: 'Win at least half of the ten rounds as a team.',
  tags: ['co-op', 'couple', 'reaction', 'communication', 'teamwork', '2 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 10,
  howToPlay: {
    objective: 'Clear ten short coordination rounds together as a team.',
    steps: [
      'Read the round brief — each round type asks for something different.',
      'Together rounds: both tap the button at the same moment.',
      'Relay rounds: whoever sees the code reads it out; the other types it in.',
      'Match rounds: agree out loud, then both pick the same symbol.',
      'Order and Signal rounds: follow the given sequence, and never tap before the cue.',
    ],
    controls: { mobile: 'Large tap targets, symbol buttons and an on-screen keypad.', desktop: 'Click or press Space to act; type the code when relaying.' },
    scoring: 'Each round won scores 100 plus a speed bonus, with a growing streak bonus. Failing a round costs 20.',
    winCondition: 'Win at least five of the ten rounds to clear the challenge.',
    timeLimit: 'Each round gives you about 9 seconds after a short brief.',
    specialRules: [
      'In a relay round the code holder cannot submit — only their partner can.',
      'Tapping before the go signal fails the round immediately.',
      'The tap window gets tighter as the match goes on.',
    ],
    playerCount: '2 players (co-op)',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const COUPLE_MEMORY_METADATA = {
  id: 'couple-memory',
  name: 'Couple Memory',
  description:
    'Cooperative memory: one partner flips the first card, the other flips its match. Clear the board as a team.',
  category: 'coop' as const,
  icon: '🃏',
  thumbnail: '🃏',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 600,
  difficulty: 'easy' as const,
  controls: 'Tap or click a face-down card to flip it.',
  rules: [
    'Ten levels, from a 4x2 board up to a full 6x6 grid.',
    'Every pair needs one card from EACH partner — you cannot flip both yourself.',
    'Matching pairs stay face up and score for the shared team total.',
    'Consecutive matches build a combo; a miss resets it and costs points.',
    'Later levels add a mistake cap and bonus pairs worth extra points.',
  ],
  scoring: 'Pair +100 (bonus pair +175), combo +25 each, level cleared +150 plus a time bonus. Miss -15, hint -40.',
  winCondition: 'Clear boards together — the score is shared by the team.',
  tags: ['co-op', 'couple', 'memory', 'cards', 'teamwork', '2 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 10,
  howToPlay: {
    objective: 'Clear the board of matching pairs with your partner before time runs out.',
    steps: [
      'One partner flips any face-down card.',
      'Describe what you saw — you both need to remember it.',
      'The OTHER partner flips the card they think matches.',
      'A correct pair stays up and scores; a miss flips both back over.',
      'Clear every pair to finish the level and move to a bigger board.',
    ],
    controls: { mobile: 'Tap a card to flip it.', desktop: 'Click a card to flip it.' },
    scoring: 'Each pair scores 100 (bonus pairs 175) plus 25 for every step of your combo. Misses cost 15 and hints cost 40.',
    winCondition: 'Clear as many of the ten levels as you can. The score is shared.',
    timeLimit: 'Each level has its own clock, from 90 to 160 seconds.',
    specialRules: [
      'You cannot flip both cards of a pair — the second card must come from your partner.',
      'From level 7 onward a mistake cap ends the run if you miss too often.',
      'Bonus pairs are worth almost double.',
    ],
    playerCount: '2 players (co-op)',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const CONNECT_FOUR_METADATA = {
  id: 'connect-four',
  name: 'Connect Four',
  description:
    'The classic drop-and-connect duel. Stack your discs and line up four in a row before your opponent does.',
  category: 'strategy' as const,
  icon: '🔴',
  thumbnail: '🔴',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'easy' as const,
  controls: 'Tap or click a column to drop your disc.',
  rules: [
    'The board is 7 columns by 6 rows. Players alternate turns.',
    'Your disc falls to the lowest free slot in the column you pick.',
    'Line up four of your discs horizontally, vertically or diagonally to win.',
    'A full column cannot be played. If the whole board fills with no four, it is a draw.',
    'Each turn has a 30 second limit — run out and the server plays for you.',
  ],
  scoring: 'Win 100, draw 40. The winning four is highlighted on the final board.',
  winCondition: 'First to connect four discs in any direction.',
  tags: ['board', 'classic', 'strategy', 'turn-based', '2 players'],
  featured: true,
  howToPlay: {
    objective: 'Be the first to line up four of your discs in a row.',
    steps: [
      'Wait for your turn — the highlighted player is on move.',
      'Tap the column you want to play.',
      'Your disc drops to the lowest free slot in that column.',
      'Build a line of four while blocking your opponent from doing the same.',
      'The server checks every direction after each move.',
    ],
    controls: { mobile: 'Tap a column to drop your disc.', desktop: 'Click a column, or press 1-7.' },
    scoring: 'A win scores 100 and a draw scores 40 for both players.',
    winCondition: 'Four of your discs in a row — horizontal, vertical or diagonal.',
    timeLimit: '30 seconds per turn.',
    specialRules: [
      'Discs always fall to the lowest free slot — you choose the column, not the row.',
      'A full column is rejected.',
      'If the board fills with nobody connecting four, the game is a draw.',
    ],
    playerCount: '2 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const HANGMAN_METADATA = {
  id: 'hangman',
  name: 'Hangman',
  description:
    'Race your opponent to uncover the hidden word. Correct letters keep your turn, wrong ones cost the whole team an attempt.',
  category: 'word' as const,
  icon: '🔤',
  thumbnail: '🔤',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 300,
  difficulty: 'easy' as const,
  controls: 'Tap a letter on the on-screen keyboard, or type it.',
  rules: [
    'Five rounds. The server picks a secret word and never sends it to your device.',
    'Players alternate guessing letters. A correct guess keeps your turn.',
    'A wrong guess costs one of the six shared attempts and passes the turn.',
    'Solving the word banks a big bonus for whoever guessed the final letter.',
    'Letters already tried cannot be guessed again.',
  ],
  scoring: 'Correct letter +15 each occurrence, streak +10, solving +100 plus 15 per attempt left. Wrong letter -8.',
  winCondition: 'Highest total score after five rounds. Equal scores are a draw.',
  tags: ['word', 'classic', 'guessing', 'turn-based', '2 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  howToPlay: {
    objective: 'Uncover the hidden word before the six attempts run out — and score more than your opponent.',
    steps: [
      'The server picks a secret word and shows you only blanks and a category hint.',
      'On your turn, guess a letter.',
      'A correct letter is revealed everywhere it appears and you keep your turn.',
      'A wrong letter costs one shared attempt and passes the turn over.',
      'Whoever reveals the last letter takes the round bonus.',
    ],
    controls: { mobile: 'Tap a letter on the on-screen keyboard.', desktop: 'Click a letter or press it on your keyboard.' },
    scoring: 'Correct letter scores 15 per occurrence with a growing streak bonus. Solving adds 100 plus 15 for every attempt left. A wrong letter costs 8.',
    winCondition: 'The higher total score after all five rounds wins.',
    timeLimit: '20 seconds per turn; a missed turn costs an attempt.',
    specialRules: [
      'The secret word is stored on the server and is only revealed once the round ends.',
      'Repeating a guessed letter is rejected and costs nothing.',
      'The six attempts are shared between both players.',
    ],
    playerCount: '2 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const SOS_GAME_METADATA = {
  id: 'sos-game',
  name: 'SOS Game',
  description:
    'Place an S or an O each turn. Spell S-O-S in any direction to score a point and immediately go again.',
  category: 'strategy' as const,
  icon: '🅾️',
  thumbnail: '🅾️',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 300,
  difficulty: 'medium' as const,
  controls: 'Pick S or O, then tap an empty cell.',
  rules: [
    'Players alternate placing a single S or O on any empty cell.',
    'Every new S-O-S line you create scores one point — horizontal, vertical or diagonal.',
    'One placement can complete several SOS lines at once; each one scores.',
    'Scoring at least one SOS earns you another turn immediately.',
    'The game ends when the board is full. Most SOS wins; equal scores are a draw.',
  ],
  scoring: '1 point per SOS line created. Multiple lines from a single placement all count.',
  winCondition: 'Most SOS lines when the board is full.',
  tags: ['board', 'strategy', 'classic', 'turn-based', '2 players'],
  featured: true,
  gridOptions: ['4x4', '5x5', '6x6', '8x8'],
  howToPlay: {
    objective: 'Create more S-O-S lines than your opponent before the board fills up.',
    steps: [
      'Choose whether you are placing an S or an O.',
      'Tap any empty cell to place that letter.',
      'Check every direction — a new S-O-S scores a point.',
      'If you score, you immediately take another turn.',
      'If you do not score, play passes to your opponent.',
    ],
    controls: { mobile: 'Tap S or O, then tap a cell.', desktop: 'Click S or O, then click a cell.' },
    scoring: 'Each new S-O-S line scores 1 point. A single placement can complete more than one line, and each is counted.',
    winCondition: 'When the board is full, the player with the most SOS lines wins. Equal scores are a draw.',
    timeLimit: '30 seconds per turn.',
    specialRules: [
      'Creating an SOS gives you another turn — chains of extra turns are possible.',
      'The same three cells are never counted twice.',
      'Board size can be set in the lobby, from 4x4 up to 8x8.',
    ],
    playerCount: '2 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const CHESS_METADATA = {
  id: 'chess',
  name: 'Chess',
  description:
    'Full legal chess with castling, en passant, promotion, check, checkmate, stalemate and a real chess clock.',
  category: 'strategy' as const,
  icon: '♟️',
  thumbnail: '♟️',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 900,
  difficulty: 'hard' as const,
  controls: 'Tap a piece to select it, then tap a highlighted square.',
  rules: [
    'Standard 8x8 chess. White moves first and players alternate.',
    'Every piece moves by the classic rules, including castling, en passant and promotion.',
    'A move that would leave your own king in check is always rejected.',
    'Checkmate wins. Stalemate, insufficient material, threefold repetition and the fifty-move rule are draws.',
    'Each player has their own clock. Running out loses on time, unless your opponent cannot mate.',
  ],
  scoring: 'Win 1000, draw 500, plus 10 per captured piece.',
  winCondition: 'Checkmate your opponent, win on time, or take a resignation.',
  tags: ['board', 'classic', 'strategy', 'chess', 'turn-based', '2 players'],
  featured: true,
  gridOptions: ['3min', '5min', '10min'],
  howToPlay: {
    objective: 'Checkmate your opponent\u2019s king — attack it so that no legal move can save it.',
    steps: [
      'White moves first. Tap one of your pieces to select it.',
      'Legal destinations are highlighted; captures are marked differently.',
      'Tap a highlighted square to move there.',
      'When a pawn reaches the far rank, choose a queen, rook, bishop or knight.',
      'Keep your king safe — the server rejects any move that leaves it in check.',
    ],
    controls: { mobile: 'Tap a piece, then tap a highlighted square.', desktop: 'Click a piece, then click a destination. Escape clears the selection.' },
    scoring: 'A win scores 1000 and a draw 500, plus 10 for every piece you capture.',
    winCondition: 'Checkmate, a win on time, or your opponent resigning.',
    timeLimit: 'Choose 3, 5 or 10 minutes per player in the lobby. The clock is kept by the server.',
    specialRules: [
      'Castling: king and rook unmoved, squares between them empty, and the king may not start, cross or land on an attacked square.',
      'En passant: a pawn that has just advanced two squares can be captured in passing, on the very next move only.',
      'Promotion: a pawn reaching the last rank becomes a queen, rook, bishop or knight of your choosing.',
      'Draws: stalemate, insufficient material, threefold repetition and the fifty-move rule are all detected automatically.',
    ],
    playerCount: '2 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const UNO_METADATA = {
  id: 'uno',
  name: 'Uno',
  description:
    'The classic colour-and-number shedding card game. Match, block with action cards, and be first to empty your hand.',
  category: 'strategy' as const,
  icon: '🃏',
  thumbnail: '🃏',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 480,
  difficulty: 'easy' as const,
  controls: 'Tap a card to play it, or tap the draw pile.',
  rules: [
    'Everyone is dealt 7 cards from a server-shuffled 108 card deck.',
    'Play a card matching the active colour or the top card\u2019s value, or play a wild.',
    'No legal card? Draw one. If it is playable you may play it straight away, otherwise your turn ends.',
    'Skip misses the next player, Reverse flips direction, Draw Two and Wild Draw Four force cards on the next player.',
    'Stacking is NOT allowed \u2014 a draw card cannot be countered with another one.',
    'Empty your hand to win the round and score the value of every opponent\u2019s remaining cards.',
  ],
  scoring:
    'Round winner scores all opponents\u2019 remaining cards: numbers at face value, action cards 20, wilds 50.',
  winCondition: 'Highest score after the final round, or the first player to reach 200 points.',
  tags: ['cards', 'classic', 'family', 'turn-based', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 3,
  howToPlay: {
    objective: 'Be the first to get rid of all your cards, then score the cards left in everyone else\u2019s hands.',
    steps: [
      'You are dealt 7 cards. Only you can see them.',
      'On your turn, play a card that matches the active COLOUR or the top card\u2019s NUMBER/SYMBOL.',
      'A wild can be played at any time \u2014 you then choose the next colour.',
      'If you have no legal card, draw one from the pile. If it is playable you may play it immediately.',
      'Play your last card to win the round.',
    ],
    controls: {
      mobile: 'Tap a highlighted card to play it. Tap the draw pile when you cannot move.',
      desktop: 'Click a card to play it; playable cards are highlighted on hover.',
    },
    scoring:
      'The round winner scores the total of every opponent\u2019s remaining cards \u2014 number cards at face value, Skip/Reverse/Draw Two 20 each, and wilds 50 each.',
    winCondition: 'The highest total score after the last round wins. Reaching 200 points ends the match early.',
    timeLimit: '30 seconds per turn. Time out and you draw a card and your turn passes.',
    specialRules: [
      'Skip: the next player loses their turn.',
      'Reverse: play changes direction. With only two players it acts as a Skip, so you play again.',
      'Draw Two / Wild Draw Four: the next player draws and loses their turn. Stacking is not allowed.',
      'Reaching one card shows UNO! automatically \u2014 there is no call button and no penalty.',
      'When the draw pile runs out the discard pile is reshuffled, keeping the top card in play.',
    ],
    playerCount: '2\u20134 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const SIM_METADATA = {
  id: 'sim',
  name: 'Sim',
  description:
    'A deceptively deep game of nerve on six dots. Claim edges \u2014 but build a triangle in your own colour and you LOSE.',
  category: 'strategy' as const,
  icon: '🔺',
  thumbnail: '🔺',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'hard' as const,
  controls: 'Tap or click an empty line between two dots.',
  rules: [
    'Six dots, and every pair can be joined \u2014 fifteen possible lines in total.',
    'Players take turns claiming one empty line in their own colour.',
    'You LOSE the moment three of YOUR OWN lines form a triangle.',
    'This is the reverse of most games: you are trying to avoid making a triangle, not to make one.',
    'With six dots a filled board always contains a triangle, so the game always produces a loser.',
  ],
  scoring: 'Win 100, draw 50. The losing triangle is highlighted on the final board.',
  winCondition: 'Your opponent loses by completing a triangle in their own colour.',
  tags: ['strategy', 'abstract', 'graph', 'classic', '2 players'],
  featured: true,
  howToPlay: {
    objective: 'Avoid ever joining three dots into a triangle using your own colour. Force your opponent to do it first.',
    steps: [
      'The board shows six dots and every possible line between them.',
      'On your turn, tap any line that has not been claimed yet.',
      'It becomes your colour permanently.',
      'Watch your own lines carefully \u2014 three of yours forming a triangle ends the game.',
      'Lines of mixed colours are completely safe; only same-colour triangles count.',
    ],
    controls: { mobile: 'Tap an empty line.', desktop: 'Click an empty line; it highlights on hover.' },
    scoring: 'A win scores 100 and a draw 50.',
    winCondition: 'You win when your OPPONENT completes a triangle in their own colour.',
    timeLimit: '30 seconds per turn. Time out and a safe line is claimed for you where possible.',
    specialRules: [
      'This is a misere game: making a triangle LOSES, it does not win.',
      'Only triangles of a single colour count \u2014 mixed triangles are harmless.',
      'By a mathematical result (Ramsey R(3,3)=6) a full board must contain a same-colour triangle, so a draw is effectively impossible.',
    ],
    playerCount: '2 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const MIRROR_GRID_METADATA = {
  id: 'mirror-grid',
  name: 'Mirror Grid',
  description:
    'Work out how a pattern looks after it is reflected, then build it. Not a copy — a genuine transformation.',
  category: 'strategy' as const,
  icon: '🪟',
  thumbnail: '🪟',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 420,
  difficulty: 'medium' as const,
  controls: 'Tap a cell to cycle symbols. Long-press or use the palette to pick a colour.',
  rules: [
    'A pattern is shown on one side of a mirror line. Build how it looks AFTER reflection.',
    'The mirror is either vertical (left ↔ right) or horizontal (top ↕ bottom) — the level tells you which.',
    'It is not a copy: a vertical mirror swaps columns, a horizontal mirror swaps rows.',
    'Every player races the same puzzle. Submit when you think it is right.',
    'A wrong submission costs points and tells you how many cells are still off — never the answer.',
  ],
  scoring: 'Level solved +200, placement bonus up to +120, plus a speed bonus. A wrong submission costs 10.',
  winCondition: 'Highest total score after the final level. Fastest server-recorded solve breaks a tie.',
  tags: ['puzzle', 'logic', 'symmetry', 'race', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  howToPlay: {
    objective: 'Build the pattern exactly as it appears after being reflected through the mirror line.',
    steps: [
      'Study the source pattern and the mirror line direction shown above the board.',
      'Work out where each symbol lands after the reflection.',
      'Tap a cell to place a symbol, and use the palette to change symbol or colour.',
      'Tap a filled cell repeatedly to cycle it, or clear it.',
      'Press Submit when you think the reflection is complete.',
    ],
    controls: {
      mobile: 'Tap a cell to place the selected symbol. Tap the palette to change symbol or colour.',
      desktop: 'Click a cell to place; click the palette to change symbol or colour.',
    },
    scoring:
      'Solving a level scores 200 plus a placement bonus (120/70/40/20) and a speed bonus of up to 150. Each wrong submission costs 10.',
    winCondition: 'The highest total score after the last level wins; the earliest server timestamp breaks ties.',
    timeLimit: '2 minutes per level.',
    specialRules: [
      'A vertical mirror line flips LEFT and RIGHT (columns swap).',
      'A horizontal mirror line flips TOP and BOTTOM (rows swap).',
      'Every player gets the identical puzzle, so the race is fair.',
      'A wrong submit tells you how many cells are still incorrect, but never which answer to use.',
    ],
    playerCount: '2\u20134 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const FUSE_METADATA = {
  id: 'fuse',
  name: 'Fuse',
  description:
    'Rotate the wire tiles until every power source reaches its own matching bulb. An abstract connection puzzle.',
  category: 'strategy' as const,
  icon: '💡',
  thumbnail: '💡',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 480,
  difficulty: 'medium' as const,
  controls: 'Tap or click a wire tile to rotate it a quarter turn.',
  rules: [
    'Each board has one or more sources and a matching bulb for each.',
    'Rotate wire tiles so a continuous path links every source to ITS OWN bulb.',
    'Two tiles connect only when both open toward each other — a one-sided opening does nothing.',
    'Sources, bulbs and blockers are fixed and cannot be rotated.',
    'A source that reaches the wrong bulb does not count. Every circuit must be correctly paired.',
  ],
  scoring: 'Level solved +250, placement bonus up to +120, plus a speed bonus. Each rotation costs 1.',
  winCondition: 'Highest total score after the final level. Fastest server-recorded solve breaks a tie.',
  tags: ['puzzle', 'logic', 'circuit', 'race', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 4,
  howToPlay: {
    objective: 'Rotate the wires until every source is connected to its own matching bulb.',
    steps: [
      'Look at the sources and the bulb that shares each one\u2019s colour.',
      'Tap a wire tile to rotate it one quarter turn.',
      'Build an unbroken path: two tiles only join when both open toward each other.',
      'Sources, bulbs and blockers are fixed \u2014 plan around them.',
      'The level completes the instant every circuit is correctly paired.',
    ],
    controls: {
      mobile: 'Tap a wire tile to rotate it clockwise.',
      desktop: 'Click a wire tile to rotate it; it highlights on hover.',
    },
    scoring:
      'Completing a board scores 250 plus a placement bonus (120/70/40/20) and a speed bonus of up to 150. Every rotation costs 1 point, so tidy solutions score better.',
    winCondition: 'The highest total score after the last board wins.',
    timeLimit: '2.5 minutes per board.',
    specialRules: [
      'A connection needs BOTH tiles to open toward each other.',
      'Connecting a source to another circuit\u2019s bulb does not count as solved.',
      'Blockers can never be rotated or connected through.',
      'Every board is generated by carving real paths first, so it is always solvable.',
    ],
    playerCount: '2\u20134 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;


export const DOMINO_MIND_METADATA = {
  id: 'domino-mind',
  name: 'Domino Mind',
  description:
    'Place dominoes to build a chain reaction, then push the starter and watch the cascade hit every target.',
  category: 'strategy' as const,
  icon: '🁣',
  thumbnail: '🁣',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 480,
  difficulty: 'hard' as const,
  controls: 'Tap an empty cell to place a domino, tap a placed one to rotate, then press Push.',
  rules: [
    'Each level has a start domino, some targets, and a small budget of dominoes you may place.',
    'A falling domino topples the first standing piece within reach along the way it faces.',
    'Only the START domino can be pushed \u2014 you must build a route to everything else.',
    'Splitters also topple sideways. Blockers stop a chain dead and never fall.',
    'The level is solved when every target has fallen and no forbidden domino has.',
  ],
  scoring: 'Level solved +250, placement bonus up to +120, plus a speed bonus. Each failed attempt costs 15.',
  winCondition: 'Highest total score after the final level. Fastest server-recorded solve breaks a tie.',
  tags: ['puzzle', 'logic', 'chain-reaction', 'race', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  howToPlay: {
    objective: 'Build a chain reaction that knocks over every target when you push the start domino.',
    steps: [
      'Find the START domino \u2014 it is the only one you are allowed to push.',
      'Tap an empty cell to place one of your dominoes, facing the way it should fall.',
      'Tap a domino you placed to rotate it, or remove it to get the budget back.',
      'Press Push to run the chain reaction.',
      'If it stops short, adjust your layout and try again \u2014 failing does not end the level.',
    ],
    controls: {
      mobile: 'Tap an empty cell to place, tap your domino to rotate, then tap Push.',
      desktop: 'Click to place and rotate; click Push to run the cascade.',
    },
    scoring:
      'Solving a level scores 250 plus a placement bonus (120/70/40/20) and a speed bonus of up to 150. Each failed attempt costs 15, so think before you push.',
    winCondition: 'The highest total score after the last level wins.',
    timeLimit: 'Each level has its own clock, from 90 seconds to just over 3 minutes.',
    specialRules: [
      'A domino topples the FIRST standing piece within reach along its facing \u2014 it cannot reach past one.',
      'Splitters also topple the two perpendicular directions.',
      'Blockers absorb a fall and stop the chain; they never topple.',
      'Forbidden dominoes must stay standing, so aim carefully.',
      'The cascade is simulated from your actual layout \u2014 change it and the result changes.',
    ],
    playerCount: '2\u20134 players',
  },
  version: '1.0.0',
} satisfies GameMetadata;
