import type { AIDifficulty } from '../types/player';
import type { GameMetadata } from '../types/game';

/**
 * Canonical game metadata, shared by the client and the server.
 *
 * Keeping this in `shared` guarantees the browser, the REST catalogue, the
 * lobby rules panel and the server registry can never drift apart.
 */

export const REACTION_RACE_METADATA = {
  id: 'reaction-race',
  name: 'Reaction Race',
  description:
    'Wait for the signal, then tap first. Tap too early and you false start. Best of five rounds wins.',
  category: 'reflex' as const,
  icon: '⚡',
  thumbnail: '⚡',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 90,
  difficulty: 'easy' as const,
  controls: 'Tap / click / press Space as fast as you can after the GO signal.',
  rules: [
    'Each round the server waits a random 1.5–5 seconds before showing GO.',
    'Tapping before GO is a false start: you score nothing this round.',
    'The first valid reaction wins the round.',
    'Reactions faster than 150ms are impossible and are rejected as false starts.',
    'Best of 5 rounds — the player with the most round wins takes the match.',
  ],
  scoring: '1 point per round won. Ties are broken by average reaction time.',
  winCondition: 'Win the most of five rounds.',
  tags: ['reflex', 'fast', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  version: '1.0.0',
} satisfies GameMetadata;


export const MEMORY_MATCH_METADATA = {
  id: 'memory-match',
  name: 'Memory Match',
  description:
    'Flip two cards, remember what you saw and collect the most pairs. The full layout never leaves the server.',
  category: 'memory' as const,
  icon: '🧠',
  thumbnail: '🧠',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'medium' as const,
  controls: 'Tap a card to flip it. Match a pair to keep your turn.',
  rules: [
    'Players take turns flipping two cards.',
    'A matching pair scores 1 point and the player continues.',
    'A mismatch flips both cards back and the turn passes on.',
    'The player with the most pairs when the board is clear wins.',
    'Only revealed cards are ever sent to clients — the hidden layout stays on the server.',
  ],
  scoring: '1 point per pair collected.',
  winCondition: 'Collect the most pairs.',
  tags: ['memory', 'turn-based', 'family', '2-4 players'],
  featured: true,
  gridOptions: ['4x4', '6x4', '6x6'],
  version: '1.0.0',
} satisfies GameMetadata;


export const WORD_RACE_METADATA = {
  id: 'word-race',
  name: 'Word Race',
  description:
    'Name as many valid words as you can in the given category before the clock runs out. The server owns the dictionary.',
  category: 'word' as const,
  icon: '🔤',
  thumbnail: '🔤',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Type a word that fits the category and press Enter.',
  rules: [
    'Each round gives a category and 60 seconds.',
    'A valid, unused word scores 1 point.',
    'Invalid or repeated words score nothing.',
    'Only the server dictionary decides what is valid — clients cannot invent words.',
    'Best of 3 rounds wins.',
  ],
  scoring: '1 point per unique valid word. Highest total after 3 rounds wins.',
  winCondition: 'Score the most valid words across three rounds.',
  tags: ['word', 'typing', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 3,
  version: '1.0.0',
} satisfies GameMetadata;


export const DOTS_AND_BOXES_METADATA = {
  id: 'dots-and-boxes',
  name: 'Dots and Boxes',
  description:
    'Draw lines, complete boxes and chain your way to victory. Completing a box earns another turn.',
  category: 'strategy' as const,
  icon: '🔲',
  thumbnail: '🔲',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 300,
  difficulty: 'medium' as const,
  controls: 'Tap the gap between two dots to draw a horizontal or vertical line.',
  rules: [
    'Players take turns drawing one horizontal or vertical line.',
    'Completing the fourth side of a box scores 1 point and earns another turn.',
    'The board is finished when every box is claimed.',
    'The player with the most boxes wins.',
  ],
  scoring: '1 point per completed box.',
  winCondition: 'Own the most boxes when the grid is full.',
  tags: ['strategy', 'turn-based', 'classic', '2-4 players'],
  featured: false,
  gridOptions: ['4x4', '6x6', '8x8'],
  version: '1.0.0',
} satisfies GameMetadata;


export const MATH_RUSH_METADATA = {
  id: 'math-rush',
  name: 'Math Rush',
  description:
    'Solve arithmetic challenges against the clock. Faster correct answers score more. The server owns every question and answer.',
  category: 'math' as const,
  icon: '🧮',
  thumbnail: '🧮',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Type your answer and press Enter (or use the on-screen keypad).',
  rules: [
    'Everyone gets the same question at the same time.',
    'A correct answer scores 10 points plus a speed bonus of up to 10.',
    'A wrong answer scores nothing and locks you out of that question.',
    'Unanswered questions score nothing when the timer runs out.',
    'Highest score after the final question wins.',
  ],
  scoring: '10 points per correct answer + up to 10 bonus points for speed.',
  winCondition: 'Score the most points across all questions.',
  tags: ['math', 'speed', 'skill', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const BATTLE_2048_METADATA = {
  id: '2048-battle',
  name: '2048 Battle',
  description:
    'Two private 2048 boards, one clock. Slide, merge and outscore your rival — the server owns every tile.',
  category: 'strategy' as const,
  icon: '🔢',
  thumbnail: '🔢',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 200,
  difficulty: 'medium' as const,
  controls: 'Arrow keys, swipe on your board or use the on-screen D-pad. Both players play at the same time.',
  rules: [
    'Each player gets their own private 4x4 board playing standard 2048.',
    'Swipe or press a direction: every tile slides and equal neighbours merge once per move.',
    'Every valid move spawns a new tile (a 2, occasionally a 4) on your board.',
    'Merging tiles adds their combined value to your score.',
    'When a board has no legal moves left it locks — that player stays in the match and waits.',
    'The match ends when both boards lock or the clock runs out; the higher score wins.',
  ],
  scoring: 'Merges add their value to your score. Higher total wins; equal totals are a draw.',
  winCondition: 'Finish with a higher score than your rival.',
  tags: ['strategy', 'puzzle', 'numbers', '2 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const MAZE_RACE_METADATA = {
  id: 'maze-race-2d',
  name: 'Maze Race 2D',
  description:
    'A maze generated fresh from the server seed — everyone races from their own start to the flag. Walls are real: only the server moves you.',
  category: 'reflex' as const,
  icon: '🧩',
  thumbnail: '🧩',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'Arrow keys, swipe or the on-screen D-pad to move one cell at a time.',
  rules: [
    'The maze is generated deterministically from the server seed — identical for everyone in the match.',
    'Every player starts from their own start cell, the same distance from the goal.',
    'Move up, down, left or right — one cell per move, walls block you.',
    'The first player to reach the flag wins rank 1; later finishers take the next ranks.',
    'Players who never reach the goal before the timeout are ranked below every finisher (closer to the goal ranks higher).',
  ],
  scoring: 'Faster finishers score more (remaining time bonus). Unfinished players score 0.',
  winCondition: 'Reach the goal first.',
  tags: ['reflex', 'maze', 'race', '2-4 players'],
  featured: false,
  gridOptions: ['11x11', '15x15', '19x19'],
  version: '1.0.0',
} satisfies GameMetadata;


export const WORD_SCRAMBLE_METADATA = {
  id: 'word-scramble-battle',
  name: 'Word Scramble Battle',
  description:
    'Unscramble the shuffled letters faster than everyone else. The original word never leaves the server until the round ends.',
  category: 'word' as const,
  icon: '🔤',
  thumbnail: '🔀',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Type what you think is the hidden word and press Enter.',
  rules: [
    'Each round the server picks a word and shuffles its letters for everyone.',
    'Type the original word and submit — first correct answer scores.',
    'Correct answers earn 1 point, plus 1 bonus point for solving in the first half of the round.',
    'Wrong answers score nothing and you can simply try again.',
    'A round ends when every active player has solved it, or when its timer runs out.',
    'The original word is revealed between rounds; after the final round the highest score wins.',
  ],
  scoring: '1 point per solved word + 1 speed bonus for early solves. Equal totals are a draw.',
  winCondition: 'Solve more words than your rivals across all rounds.',
  tags: ['word', 'typing', 'puzzle', '2-4 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 5,
  version: '1.0.0',
} satisfies GameMetadata;


export const SHAPE_MATCH_METADATA = {
  id: 'shape-match-battle',
  name: 'Shape Match Battle',
  description:
    'Spot the shape that matches the target — fast, sharp eyes win. The correct option is decided by the server alone.',
  category: 'reflex' as const,
  icon: '🔶',
  thumbnail: '🔶',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 130,
  difficulty: 'easy' as const,
  controls: 'Tap the option that matches the target shape.',
  rules: [
    'Every round shows one target shape and four options — exactly one matches.',
    'Tap an option: a correct match scores 1 point, plus 1 bonus point in the first half of the round.',
    'A wrong option scores nothing — you only get one pick per round.',
    'The round ends when every active player has picked, or when its timer runs out.',
    'After the final round the highest score wins; equal scores are a draw.',
  ],
  scoring: '1 point per correct match + 1 speed bonus for fast picks.',
  winCondition: 'Match more shapes than your rivals.',
  tags: ['reflex', 'pattern', 'speed', '2-4 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 10,
  version: '1.0.0',
} satisfies GameMetadata;


export const SNAKE_BATTLE_METADATA = {
  id: 'snake-battle',
  name: 'Snake Battle',
  description:
    'Two snakes, one arena. Grab the food, cut off your rival and be the last serpent sliding. The server moves every snake on a fixed clock.',
  category: 'reflex' as const,
  icon: '🐍',
  thumbnail: '🐍',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Steer with WASD / arrow keys, swipe on the arena or use the D-pad below it.',
  rules: [
    'Both snakes slide on the same 17x17 grid, one cell every quarter second.',
    'Turn up, down, left or right — reversing into yourself is rejected by the server.',
    'Eating food grows your snake by one segment and scores 10 points.',
    'Hitting a wall, any snake body or another head kills your snake instantly.',
    'A dead snake is out, but the survivor keeps eating until the clock or their own crash.',
    'Survive longer to win; if both die on the same step the higher score takes it.',
  ],
  scoring: '10 points per food. Survival beats score; score breaks survival ties.',
  winCondition: 'Outlive your rival (or outhunt them on the fatal step).',
  tags: ['reflex', 'arcade', 'classic', '2 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const TRAFFIC_DODGE_METADATA = {
  id: 'traffic-dodge-race',
  name: 'Traffic Dodge Race',
  description:
    'A five-lane arcade sprint: weave through oncoming traffic, survive the crashes and outrun your rival to the finish line.',
  category: 'reflex' as const,
  icon: '🏎️',
  thumbnail: '🏎️',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'Switch lanes with A/D, the left/right arrow keys, swipe or the side buttons.',
  rules: [
    'Both racers share one five-lane road and accelerate automatically — steering is all you do.',
    'Traffic ahead of you is generated from the server seed; every racer sees the same road.',
    'Hitting a car stuns you for 1.5 seconds and drops you behind it — the race goes on.',
    'The finish line is 2000 units away; the first racer across wins.',
    'If the clock runs out, the racer closest to the finish wins.',
  ],
  scoring: 'Progress decides: finishing first wins, otherwise the furthest racer takes it.',
  winCondition: 'Cross the finish line first (or lead at the timeout).',
  tags: ['reflex', 'racing', 'arcade', '2 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const TARGET_RUSH_METADATA = {
  id: 'target-rush',
  name: 'Target Rush',
  description:
    'Three targets, one symbol to hit. Read the prompt, tap the right target first and build a streak your rival cannot match.',
  category: 'reflex' as const,
  icon: '🎯',
  thumbnail: '🎯',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 120,
  difficulty: 'easy' as const,
  controls: 'Tap or click the target that matches the prompt symbol.',
  rules: [
    'Every round shows a prompt symbol and three large targets — exactly one matches.',
    'The first correct tap scores: 10 points, up to 10 extra for speed, plus a combo bonus for your streak.',
    'Tapping a wrong target scores nothing, breaks your streak and locks you out for a second.',
    'A round ends on the first correct tap or when its timer runs out (all streaks reset).',
    'Eight rounds — the highest total score wins, equal totals are a draw.',
  ],
  scoring: '10 points per hit + up to 10 speed points + 2 per streak step (max +6).',
  winCondition: 'Score the most points across eight rounds.',
  tags: ['reflex', 'speed', 'focus', '2 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 8,
  version: '1.0.0',
} satisfies GameMetadata;


export const CAPTURE_THE_FLAG_METADATA = {
  id: 'capture-the-flag-2d',
  name: 'Capture the Flag 2D',
  description:
    'Sneak across the arena, grab the enemy flag and carry it home — but one touch sends you back to your base. First team to three captures.',
  category: 'strategy' as const,
  icon: '🚩',
  thumbnail: '🚩',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Move one cell at a time with WASD / arrow keys, swipe or the D-pad.',
  rules: [
    'Two teams: with four players, seats 1 & 3 face seats 2 & 4; with two it is a duel.',
    'Enter the enemy flag cell to pick the flag up — it moves with you.',
    'Carry it onto your own base to score a capture; first team to 3 captures wins.',
    'Moving onto an opponent tags them: they respawn at their base and any carried flag returns home.',
    'Players standing on their own base cannot be tagged (no spawn camping).',
    'If the clock runs out, the team with more captures wins.',
  ],
  scoring: '1 point per captured flag for the whole team.',
  winCondition: 'Reach 3 captures or lead when the clock ends.',
  tags: ['strategy', 'teams', 'arcade', '2-4 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const PADDLE_DUEL_METADATA = {
  id: 'paddle-duel',
  name: 'Paddle Duel',
  description:
    'Classic paddle versus paddle. Keep the ball in play, angle your returns and outlast your rival — first to the point limit takes the duel.',
  category: 'reflex' as const,
  icon: '🏓',
  thumbnail: '🏓',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Slide your paddle with W/S, the up/down arrow keys, or drag on your side of the arena.',
  rules: [
    'Both paddles live on the server — the ball is simulated there on a fixed clock.',
    'The ball bounces off the top and bottom walls; returning it speeds it up a little.',
    'Hit the ball with the edge of your paddle to angle it sharply.',
    'If the ball passes your paddle your rival scores a point.',
    'First to 7 points (configurable 3–15) wins; at the 3-minute timeout the leader takes it.',
  ],
  scoring: '1 point per rally won by your opponent missing the ball.',
  winCondition: 'Reach the point limit first, or lead when the clock ends.',
  tags: ['reflex', 'arcade', 'classic', '2 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 7,
  version: '1.0.0',
} satisfies GameMetadata;


export const BRICK_BREAKER_METADATA = {
  id: 'brick-breaker-battle',
  name: 'Brick Breaker Battle',
  description:
    'Two identical arenas, one mirrored brick wall each. Break your wall faster, chain combos and bank more points than your rival before the clock or your lives run out.',
  category: 'reflex' as const,
  icon: '🧱',
  thumbnail: '🧱',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Slide your paddle with A/D, the left/right arrow keys, mouse or by dragging on your arena.',
  rules: [
    'Each player breaks their own identical wall — the server simulates both balls.',
    'Bricks are worth more the higher they sit: 10 to 30 points.',
    'Chain bricks without touching your paddle to multiply them, up to x4.',
    'Missing the ball costs a life; you have three, then your run is over.',
    'Clearing the whole wall banks a 100-point bonus — most points in 3 minutes wins.',
  ],
  scoring: 'Brick points x combo multiplier (up to x4) + 100 for a full clear.',
  winCondition: 'Score the most points (ties: earlier finish, then lives left).',
  tags: ['reflex', 'arcade', 'classic', '2 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const PATTERN_MEMORY_METADATA = {
  id: 'pattern-memory-battle',
  name: 'Pattern Memory Battle',
  description:
    'Watch the tiles flash, then replay the sequence from memory. The patterns grow longer every round — who can keep up longest?',
  category: 'memory' as const,
  icon: '🔮',
  thumbnail: '🔮',
  minPlayers: 2,
  maxPlayers: 2,
  supportedPlayerCounts: [2],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Watch the flashes, then tap the tiles in the same order.',
  rules: [
    'Both players memorise the exact same server-generated sequence.',
    'The pattern starts at three tiles and grows by one every two rounds.',
    'Replay it in order: every correct tap advances you, one wrong tap ends your attempt.',
    'A full replay scores pattern length x 10, a speed bonus and a streak bonus.',
    'Eight rounds — the highest total wins, equal totals are a draw.',
  ],
  scoring: '10 per tile + up to 5 per tile for speed + a streak bonus (max +6).',
  winCondition: 'Score the most points across eight rounds.',
  tags: ['memory', 'focus', 'party', '2 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 8,
  version: '1.0.0',
} satisfies GameMetadata;


export const BOMB_PASS_METADATA = {
  id: 'bomb-pass-2d',
  name: 'Bomb Pass 2D',
  description:
    'A cartoon firework is ticking and nobody wants to be holding it. Pass it around, watch the fuse shrink and dodge three strikes across eight frantic rounds.',
  category: 'reflex' as const,
  icon: '🧨',
  thumbnail: '🧨',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Tap a player to pass them the firework before the fuse burns out.',
  rules: [
    'A purely fictional cartoon firework starts with a random player and a server-timed fuse.',
    'Only the holder can pass, and only to someone still in the game (never to themselves).',
    'You must hold the firework for a moment before passing it on — no instant ping-pong.',
    'Holding it when the fuse ends costs a strike; everyone else scores a point.',
    'Three strikes and you are out. Last player standing, or fewest strikes after eight rounds, wins.',
  ],
  scoring: '1 point for surviving a round you are not holding the firework in.',
  winCondition: 'Be the last player standing, or have the fewest strikes after eight rounds.',
  tags: ['reflex', 'party', 'hot-potato', '2-4 players'],
  featured: false,
  hasRounds: true,
  defaultRounds: 8,
  version: '1.0.0',
} satisfies GameMetadata;


export const DRAW_GUESS_METADATA = {
  id: 'draw-guess-battle',
  name: 'Draw & Guess Battle',
  description:
    'Take turns as the drawer. Sketch a secret word on a 2D canvas while everyone else races to guess it. The word never leaves the server.',
  category: 'word' as const,
  icon: '🎨',
  thumbnail: '🎨',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'easy' as const,
  controls: 'Draw with your finger or mouse. Type guesses and press Enter. Brush, eraser and a simple palette.',
  rules: [
    'Each round one player is the drawer and receives a secret word nobody else can see.',
    'The drawer sketches on a shared 2D canvas; strokes are sent as points, never a screenshot.',
    'Everyone else types guesses. The first correct guess scores the most; later solvers score less.',
    'The drawer earns a bonus for every unique solver.',
    'A round ends when every guesser has solved it, or when the timer runs out.',
    'After several rounds the highest score wins.',
  ],
  scoring: 'First guess 100, then 75 / 50 / 25. Drawer +40 per unique solver.',
  winCondition: 'Score the most points across all drawing rounds.',
  tags: ['word', 'party', 'drawing', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 6,
  version: '1.0.0',
} satisfies GameMetadata;


export const SECRET_ROLE_METADATA = {
  id: 'secret-role',
  name: 'Secret Role',
  description:
    'A family-friendly deduction game. Most players share a secret location — one Secret Agent does not. Clue, vote, and catch the agent (or blend in).',
  category: 'strategy' as const,
  icon: '🕵️',
  thumbnail: '🕵️',
  minPlayers: 3,
  maxPlayers: 4,
  supportedPlayerCounts: [3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 300,
  difficulty: 'medium' as const,
  controls: 'On your turn type a short clue. Then vote for who you think is the Secret Agent. The agent may guess the location.',
  rules: [
    'Each round the server assigns one Secret Agent; everyone else is a Citizen who knows the location.',
    'Roles are private: you only ever see your own role and (if you are a Citizen) the location.',
    'Players take turns giving a short clue about the location without naming it.',
    'After clues, everyone votes for one other player. Majority on the agent → Citizens win the round.',
    'The Secret Agent may guess the location. A correct guess wins the round for the agent.',
    'If the agent is not voted out, the agent wins the round.',
  ],
  scoring: 'Citizen correct vote +100. Agent survives +150. Agent guesses the location +200.',
  winCondition: 'Highest cumulative score after all rounds.',
  tags: ['strategy', 'party', 'deduction', '3-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 4,
  version: '1.0.0',
} satisfies GameMetadata;


export const PLATFORM_DASH_METADATA = {
  id: 'platform-dash-2d',
  name: 'Platform Dash 2D',
  description:
    'Race the same short 2D course. Jump, ride moving platforms, bounce on pads and hit checkpoints — the server simulates every step.',
  category: 'reflex' as const,
  icon: '🏃',
  thumbnail: '🏃',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Mobile: left / right / jump buttons. Desktop: A/D or arrows, Space or Arrow Up to jump.',
  rules: [
    'Everyone races the same server-picked 2D course (Summit, Caves or Skyway).',
    'Move and jump — the server owns position, velocity, collisions and the finish line.',
    'Falling respawns you at your last checkpoint with a short freeze; you are not eliminated.',
    'Jump pads launch you up; moving and crumbling platforms are simulated on the server clock.',
    'First to the flag wins rank 1; later finishers take the next ranks. Timeout ranks by distance.',
  ],
  scoring: '1st 100, 2nd 75, 3rd 50, 4th 25. Unfinished runners score 0.',
  winCondition: 'Reach the finish first (or lead in distance when the clock ends).',
  tags: ['reflex', 'platformer', 'race', '2-4 players'],
  featured: false,
  gridOptions: ['summit', 'caves', 'skyway'],
  version: '1.0.0',
} satisfies GameMetadata;


export const COLOR_CLASH_METADATA = {
  id: 'color-clash',
  name: 'Color Clash',
  description:
    'Fast colour-selection rounds with a twist: sometimes tap the named colour, sometimes the ink, sometimes the colour you just saw. Labels keep it accessible.',
  category: 'reflex' as const,
  icon: '🌈',
  thumbnail: '🌈',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Tap the colour that matches the instruction. Buttons are large, labelled, and colour-coded.',
  rules: [
    'Each round the server picks a challenge type and the correct colour — clients never decide.',
    'Name: tap the colour that is named. Stroop: tap the ink colour, not the written word.',
    'Memory: a colour flashes, then you pick it from the options. Race: one tile is the target.',
    'The fastest correct tap scores the most; later correct taps score less. A wrong tap scores 0.',
    'One pick per round. After 12 rounds the highest score wins.',
  ],
  scoring: 'Fastest correct 100, then 75 / 50 / 25. Wrong answers score 0.',
  winCondition: 'Score the most points across twelve rounds.',
  tags: ['reflex', 'colour', 'speed', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 12,
  version: '1.0.0',
} satisfies GameMetadata;


export const TERRITORY_RUSH_METADATA = {
  id: 'territory-rush',
  name: 'Territory Rush',
  description:
    'Claim the map. Leave your home, loop a trail and close it to paint the enclosed cells. Cut a rival trail to send them home. Largest territory when the clock ends wins.',
  category: 'reflex' as const,
  icon: '🗺️',
  thumbnail: '🗺️',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Steer with WASD / arrows, swipe or the D-pad. The server moves everyone on its clock.',
  rules: [
    'Everyone starts with a small home territory. You are safe on your own colour.',
    'Leaving home lays a trail. Close a loop back to your land to capture the enclosed cells.',
    'Your trail is vulnerable: a rival stepping on it sends you home. Hitting your own trail does the same.',
    'You cannot leave the map. Homes cannot be stolen.',
    'When the clock ends, the largest territory wins.',
  ],
  scoring: '1 point per owned cell. Ties broken by successful captures, then fewer deaths.',
  winCondition: 'Own the most cells when the timer ends.',
  tags: ['reflex', 'territory', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const HEXA_CONQUEST_METADATA = {
  id: 'hexa-conquest',
  name: 'Hexa Conquest',
  description:
    'Expand across a hex map one adjacent tile at a time. Bonus tiles score extra, energy tiles fuel a Bridge special, and blocked tiles stay empty. Most territory when the board or clock ends wins.',
  category: 'strategy' as const,
  icon: '⬡',
  thumbnail: '⬡',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 240,
  difficulty: 'medium' as const,
  controls: 'Tap an adjacent hex on your turn. Use Bridge to claim one non-adjacent tile.',
  rules: [
    'Players take timed turns. Capture a hex adjacent to your territory.',
    'Normal tiles score 1, bonus tiles score 2, energy tiles grant a Bridge charge.',
    'Blocked tiles cannot be captured. Starting hexes cannot be stolen.',
    'Bridge (limited) claims one unowned hex that is not adjacent.',
    'If the turn timer expires the turn passes. Highest score when the board fills or the match clock ends wins.',
  ],
  scoring: 'Tile value: normal 1, bonus 2, energy 1. Highest total wins.',
  winCondition: 'Hold the highest territory score when the match ends.',
  tags: ['strategy', 'hex', 'turn-based', '2-4 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const COLOR_TRAILS_METADATA = {
  id: 'color-trails',
  name: 'Color Trails',
  description:
    'A fast arcade dash: leave a fading coloured trail, scoop matching pickups, hit matching zones for combos, and avoid rival trails.',
  category: 'reflex' as const,
  icon: '🌀',
  thumbnail: '🌀',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Steer with WASD / arrows, swipe or the D-pad. Trails fade on the server clock.',
  rules: [
    'You always leave a short fading trail. Trails are not permanent territory.',
    'Pick up a colour token: +10 and your combo colour updates.',
    'Ride into a matching colour zone for +25 times your combo.',
    'Clipping an opponent trail costs points, resets combo and briefly freezes you.',
    'Highest score when the timer ends wins.',
  ],
  scoring: 'Pickup +10, matching zone +25 × combo. Trail hits −10.',
  winCondition: 'Score the most points before the clock ends.',
  tags: ['reflex', 'arcade', 'colour', '2-4 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const COIN_HUNTERS_METADATA = {
  id: 'coin-hunters-arena',
  name: 'Coin Hunters Arena',
  description:
    'Dash around a shared arena vacuuming coins. Gold and rare coins pay more, multipliers and bonus zones juice the haul, and a roaming blocker keeps you honest.',
  category: 'reflex' as const,
  icon: '🪙',
  thumbnail: '🪙',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Move with WASD / arrows, swipe or the D-pad. Collection is confirmed by the server.',
  rules: [
    'The server spawns coins: normal +10, gold +25, rare +50, multiplier 2× for a few seconds.',
    'Stand on a coin (or send collect) — distance and identity are checked server-side.',
    'A 2× bonus zone doubles collections while you stand in it. Slow tiles double your step time.',
    'A moving blocker occupies a cell; walking into it bounces you back.',
    'Duplicate collects award nothing. Highest score when the timer ends wins.',
  ],
  scoring: 'Coin value × active multiplier (personal 2× and/or bonus zone 2×).',
  winCondition: 'Hold the highest score when the arena clock ends.',
  tags: ['reflex', 'arcade', 'collection', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const CASTLE_SIEGE_METADATA = {
  id: 'castle-siege-2d',
  name: 'Castle Siege 2D',
  description:
    'Defend your keep, raise walls and towers, capture the midfield and bombard rival castles. Energy, damage and captures are all server owned.',
  category: 'strategy' as const,
  icon: '🏰',
  thumbnail: '🏰',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 180,
  difficulty: 'medium' as const,
  controls: 'Move with WASD / arrows / D-pad. Build, upgrade, fire and capture with the action buttons.',
  rules: [
    'Each player owns a castle with 100 hit points and a commander on the 2D field.',
    'Energy regenerates on the server clock. Spend it to build walls, upgrade towers or fire.',
    'Towers auto-fire at nearby commanders. Walls block movement and shots.',
    'Stand on a capture node to earn hold points. Destroy every rival castle, or lead when the clock ends.',
    'The server validates range, cooldowns, cost, damage and captures — clients never set HP.',
  ],
  scoring: 'Damage dealt + capture holds + remaining castle HP. Last castle standing wins outright.',
  winCondition: 'Destroy every other castle, or hold the highest score when time expires.',
  tags: ['strategy', 'defense', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const TRAFFIC_CONTROL_METADATA = {
  id: 'traffic-control-battle',
  name: 'Traffic Control Battle',
  description:
    'Run your own intersection. Flip the lights, clear waves of cars and avoid jams — the server drives every vehicle.',
  category: 'reflex' as const,
  icon: '🚦',
  thumbnail: '🚦',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'Tap Switch lights (or press Space / L) to flip north-south vs east-west green.',
  rules: [
    'Each player has a private crossroads. Cars spawn from four approaches.',
    'Only one axis can be green. Cars wait on red and drive on green.',
    'A car that exits scores. A jam (queue too long) is a penalty. Collisions in the box cost more.',
    'Waves get faster as the match goes on. Highest valid score when the timer ends wins.',
    'The server spawns, moves and scores every car. Clients only send light intents.',
  ],
  scoring: '+10 per cleared car, −15 per jam, −25 per collision. Equal scores are a draw.',
  winCondition: 'Hold the highest score when the clock ends.',
  tags: ['reflex', 'strategy', 'arcade', '2-4 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const MAGNET_MAZE_METADATA = {
  id: 'magnet-maze',
  name: 'Magnet Maze',
  description:
    'A top-down 2D maze race with magnetic currents. Flip your polarity, ride or fight the pull, collect crystals and reach the finish.',
  category: 'reflex' as const,
  icon: '🧲',
  thumbnail: '🧲',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / swipe / D-pad to step. Flip polarity with F or the polarity button.',
  rules: [
    'Everyone races the same seeded 2D maze. Walls are real — only the server moves you.',
    'Magnet tiles pull you with your polarity, or push you if you flip it.',
    'Collect crystals for points. Spikes freeze you briefly. The finish cell must be occupied on the server.',
    'You cannot declare a finish yourself. First verified arrival ranks 1; timeout ranks by crystals then distance.',
  ],
  scoring: 'Crystals + finish bonus. Faster verified finishers rank higher.',
  winCondition: 'Reach the finish first (or lead crystals/distance if nobody finishes).',
  tags: ['reflex', 'puzzle', 'maze', '2-4 players'],
  featured: false,
  version: '1.0.0',
} satisfies GameMetadata;


export const SHOP_RUSH_METADATA = {
  id: 'shop-rush-battle',
  name: 'Shop Rush Battle',
  description:
    'Race the aisles with a private shopping list. Grab the right items, dump bonus candy and check out before the clock.',
  category: 'strategy' as const,
  icon: '🛒',
  thumbnail: '🛒',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'easy' as const,
  controls: 'Move with WASD / arrows / swipe / D-pad. Pick up on a shelf, check out on the till.',
  rules: [
    'Each shopper gets a private 3-item list. Inventory holds at most 3 items.',
    'Stand on a shelf and pick to collect. Only the server grants the item.',
    'Bonus candy is never on the list but pays extra at checkout.',
    'Checkout scores matching list items and candy, then deals a fresh list. Wrong items stay in the basket.',
    'Highest checkout score when time ends wins. Lists of other players never leave the server.',
  ],
  scoring: '+40 per listed item, +25 candy, +50 list-complete bonus.',
  winCondition: 'Hold the highest checkout score when the shop closes.',
  tags: ['strategy', 'collection', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const SHADOW_COPY_METADATA = {
  id: 'shadow-copy-battle',
  name: 'Shadow Copy Battle',
  description:
    'Move, collect and flip plates — then your previous path returns as a Shadow Copy. Plan this round so last round’s ghost holds a switch for you.',
  category: 'strategy' as const,
  icon: '🌑',
  thumbnail: '🌑',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / swipe / D-pad to step one cell. The server records every legal step.',
  rules: [
    'Each short round you walk a 2D arena collecting crystals and standing on plates.',
    'The server stores your validated steps. Next round a Shadow Copy replays them on the same clock.',
    'Plates stay active while you or your shadow stand on them. Gates open only when every plate is held.',
    'Gold crystals are yours. Violet crystals can only be collected by a Shadow Copy.',
    'Shadows skip a blocked step and stay put — they never teleport and clients cannot submit a path.',
  ],
  scoring: 'Player crystal +100, shadow crystal +50, exit +75, efficient route +20. Highest total wins.',
  winCondition: 'Hold the highest score after three rounds.',
  tags: ['strategy', 'puzzle', 'shadow', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 3,
  gridOptions: ['twin-plates', 'shadow-vault', 'relay-gate', 'split-loops', 'hazard-run'],
  version: '1.0.0',
} satisfies GameMetadata;


export const ECHO_MAZE_METADATA = {
  id: 'echo-maze',
  name: 'Echo Maze',
  description:
    'Memorise the maze in a short preview, then race through fog. Your echo trail shows where you have already walked.',
  category: 'memory' as const,
  icon: '🌀',
  thumbnail: '🌀',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / swipe / D-pad. Walls stay real even when the fog hides them.',
  rules: [
    'A short preview shows the full maze. Then selected walls vanish into fog.',
    'Move one cell at a time. Hidden walls still block you — the server owns collisions.',
    'Checkpoints score extra. Your echo trail is the last few validated steps.',
    'Reach the exit first (or with the highest score) before the clock ends.',
  ],
  scoring: 'Finish +100, checkpoint +50, leftover time bonus. Highest total wins.',
  winCondition: 'Hold the highest score when every runner finishes or the clock ends.',
  tags: ['memory', 'maze', 'race', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 2,
  version: '1.0.0',
} satisfies GameMetadata;


export const FAKE_DOOR_METADATA = {
  id: 'fake-door-battle',
  name: 'Fake Door Battle',
  description:
    'Four doors, one safe route. Read the clue, remember last round, and skip the fakes — the server owns the answer.',
  category: 'memory' as const,
  icon: '🚪',
  thumbnail: '🚪',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Tap a door (or keys 1–4). Clues are colour, symbol, number, position or memory.',
  rules: [
    'Each round shows four doors and one learnable clue. Exactly one door is safe.',
    'A correct pick advances you. A fake door costs time and scores nothing.',
    'Clues are never random: colour match, unique symbol, even number, far-right, or last-round memory.',
    'The correct door never leaves the server until the reveal.',
  ],
  scoring: 'Correct door +100 plus a speed bonus. Highest total after five rounds wins.',
  winCondition: 'Score the most points across five rounds.',
  tags: ['memory', 'puzzle', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  version: '1.0.0',
} satisfies GameMetadata;


export const MOVING_ISLAND_METADATA = {
  id: 'moving-island',
  name: 'Moving Island',
  description:
    'Hop across 2D platforms that slide, blink and spin. Grab checkpoints before the islands drift away.',
  category: 'reflex' as const,
  icon: '🏝️',
  thumbnail: '🏝️',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / swipe / D-pad to step onto a neighbouring platform cell.',
  rules: [
    'Platforms slide, blink or rotate on the server clock. Falling respawns you at your last checkpoint.',
    'Stand on a checkpoint to lock it. Coins on islands score extra.',
    'Reach the flag cell to finish. Nobody is eliminated for falling.',
    'The server moves every platform and validates every step.',
  ],
  scoring: 'Coin +10, checkpoint +25, finish +100. Highest total when the clock ends wins.',
  winCondition: 'Hold the highest score when time expires (finishers rank first on a tie).',
  tags: ['reflex', 'platformer', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const MAGNET_THIEF_METADATA = {
  id: 'magnet-thief',
  name: 'Magnet Thief',
  description:
    'Vacuum coins with a directional magnet, then steal a rival gem if you are in range. Ownership is server-side.',
  category: 'strategy' as const,
  icon: '🧲',
  thumbnail: '💎',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Move with WASD / arrows / D-pad. Magnet with Q/E or the magnet buttons (direction + activate).',
  rules: [
    'Step onto a coin to collect it. The server grants the points.',
    'Activate your magnet in a direction to pull nearby coins one cell toward you (cooldown applies).',
    'A carried gem can be stolen if you magnetise within range and the owner is not in a safe corner.',
    'Magnetic zones double range. Clients cannot assign themselves an object.',
  ],
  scoring: 'Coin +10, gem +50 (held at the buzzer). Highest valid total wins.',
  winCondition: 'Hold the highest score when the arena clock ends.',
  tags: ['strategy', 'collection', 'arcade', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const REVERSE_RACE_METADATA = {
  id: 'reverse-race',
  name: 'Reverse Race',
  description:
    'Every round flips the objective: finish first, finish second, hit an exact time, collect exactly N, or stop in the zone.',
  category: 'reflex' as const,
  icon: '🔄',
  thumbnail: '🔄',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / swipe / D-pad. The current objective is shown above the track.',
  rules: [
    'Each round the server publishes a new target. Reaching the flag first is not always the win.',
    'Objectives include exact time, second place, collect exactly N tokens, or stop inside the zone.',
    'Movement, tokens, finish times and ranks are validated on the server.',
    'Highest total after every round wins.',
  ],
  scoring: 'Up to 100 per round based on how closely you match the published objective.',
  winCondition: 'Hold the highest score after four rounds.',
  tags: ['reflex', 'race', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 4,
  version: '1.0.0',
} satisfies GameMetadata;


export const MIRROR_ARENA_METADATA = {
  id: 'mirror-arena',
  name: 'Mirror Arena',
  description:
    'Every step you take is mirrored across the arena. Use your twin to hold plates, grab crystals and open the gate.',
  category: 'strategy' as const,
  icon: '🪞',
  thumbnail: '🪞',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 150,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / swipe / D-pad. Your mirror always moves opposite you.',
  rules: [
    'Your mirror is at (width-1-x, y). It is not a second player — it is you, flipped.',
    'Plates stay active while you or a mirror stand on them. Gates open only when every plate is held.',
    'Crystals can be collected by you or your mirror. Hazards freeze you briefly.',
    'The exit only scores while the gates are open. The server owns collisions and the mirror.',
  ],
  scoring: 'Crystal +20, exit +80. Highest total when the clock ends wins.',
  winCondition: 'Hold the highest score when time expires (exiters rank first on a tie).',
  tags: ['strategy', 'puzzle', 'mirror', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const CHAIN_REACTION_METADATA = {
  id: 'chain-reaction-battle',
  name: 'Chain Reaction Battle',
  description:
    'Trigger one node and watch the board cascade. Long, high-value chains win — the server owns every spark.',
  category: 'strategy' as const,
  icon: '💥',
  thumbnail: '💥',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'Tap a node to trigger it. Two triggers per round.',
  rules: [
    'Each round the server deals a coloured board of normal, bonus, multiplier, blocker and arrow nodes.',
    'Trigger a node: same-colour neighbours chain. Arrows continue in their direction. Blockers never chain.',
    'You get two triggers per round. Clients submit a node id — never a chain length.',
    'Highest total after four rounds wins.',
  ],
  scoring: 'Chain length × 10 × multipliers, plus 15 per bonus node in the chain.',
  winCondition: 'Score the most points across four rounds.',
  tags: ['strategy', 'puzzle', 'party', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 4,
  version: '1.0.0',
} satisfies GameMetadata;


export const ONE_BUTTON_METADATA = {
  id: 'one-button-battle',
  name: 'One Button Battle',
  description:
    'One button, many contexts. Jump, dash, dodge, switch, collect or shield — only if you press in the window.',
  category: 'reflex' as const,
  icon: '🔘',
  thumbnail: '🔘',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 120,
  difficulty: 'medium' as const,
  controls: 'One large action button, or Space. Timing is everything.',
  rules: [
    'A sequence of events approaches. The current context (jump, dash, dodge, switch, collect, shield) is shown.',
    'Press in the timing window to succeed. Early or late presses miss and break your streak.',
    'The server owns the window, the context and the score. Clients only send tap.',
    'Highest score after the sequence wins.',
  ],
  scoring: 'Hit +20 plus 5 per streak step. Misses score 0 and reset the streak.',
  winCondition: 'Score the most points across the event sequence.',
  tags: ['reflex', 'timing', 'party', '2-4 players'],
  featured: true,
  version: '1.0.0',
} satisfies GameMetadata;


export const SPLIT_WORLD_METADATA = {
  id: 'split-world',
  name: 'Split World',
  description:
    'See different versions of the same world. Share clues, work together, and find the way out.',
  category: 'strategy' as const,
  icon: '🌍',
  thumbnail: '🌍',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 260,
  difficulty: 'hard' as const,
  controls: 'WASD / arrows / swipe / D-pad. Chat is part of the puzzle.',
  rules: [
    'Five rounds, five arenas: a gate, a key vault, a switch order, pressure plates and an extraction.',
    'The true layout lives on the server. Each seat gets a different lens on the same world.',
    'Wardens see switches and the exit, Gatekeepers see hazards and the gate, Scouts see keys and traps.',
    'Decoy tiles look real to some lenses but are plain floor — only chat separates truth from bait.',
    'Real walls and closed gates block everyone. Hidden tiles and secret orders never leave the server.',
  ],
  scoring:
    'Switch +30, key +25, plate +20, exit +100 plus a speed bonus, round win +25. Hazards and wrong order cost points.',
  winCondition: 'Hold the highest total score after five rounds (rounds won breaks a tie).',
  tags: ['strategy', 'coop', 'puzzle', 'communication', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 5,
  version: '2.0.0',
} satisfies GameMetadata;


export const INVISIBLE_PATH_METADATA = {
  id: 'invisible-path',
  name: 'Invisible Path',

  description:
    'Memorise the glowing path, then cross the grid after it vanishes. Wrong tiles bounce you back.',
  category: 'memory' as const,
  icon: '✨',
  thumbnail: '✨',
  minPlayers: 2,
  maxPlayers: 4,
  supportedPlayerCounts: [2, 3, 4],
  hasAI: true,
  aiDifficulties: ['easy', 'medium', 'hard'] as AIDifficulty[],
  estimatedDuration: 140,
  difficulty: 'medium' as const,
  controls: 'WASD / arrows / swipe / D-pad. Only the server knows which tiles stay safe.',
  rules: [
    'A short preview shows the safe path (and a few decoy tiles). Then everything hides.',
    'Step onto a safe tile to continue. A wrong tile stuns you and returns you to your last safe cell.',
    'Checkpoints along the path score extra. Reach the finish cell to bank the round.',
    'Paths grow longer each round. The safe set never leaves the server during play.',
  ],
  scoring: 'Safe step +5, checkpoint +30, finish +80, wrong tile −10. Highest total wins.',
  winCondition: 'Hold the highest score after three rounds.',
  tags: ['memory', 'puzzle', 'race', '2-4 players'],
  featured: true,
  hasRounds: true,
  defaultRounds: 3,
  version: '1.0.0',
} satisfies GameMetadata;
