/**
 * Server-owned dictionary for Word Scramble Battle.
 *
 * The client never receives this list: the server picks a word per round and
 * only the scrambled letters are broadcast. The original word is revealed
 * after the round has ended.
 */
export const SCRAMBLE_WORDS: string[] = [
  'PLANET', 'GARDEN', 'MARKET', 'SILVER', 'BRIDGE', 'CANDLE', 'DANGER', 'FRIEND',
  'GHOST', 'ISLAND', 'JUNGLE', 'KITTEN', 'LEMON', 'MAGIC', 'NOBLE', 'ORANGE',
  'PIANO', 'QUEST', 'RIVER', 'SINGER', 'TIGER', 'UNCLE', 'VIOLIN', 'WINTER',
  'YELLOW', 'ZEBRA', 'ANCHOR', 'BOTTLE', 'CASTLE', 'DINNER', 'ENGINE', 'FOREST',
  'GALAXY', 'HAMMER', 'IGLOO', 'JACKET', 'LADDER', 'MONKEY', 'NESTLE', 'OYSTER',
  'PARROT', 'QUARREL', 'ROCKET', 'SANDAL', 'TEMPLE', 'UMBRELLA', 'VULTURE', 'WALNUT',
  'BALLOON', 'COMPASS', 'DOLPHIN', 'ELEPHANT', 'FESTIVAL', 'GRAPES', 'HARBOUR', 'LANTERN',
  'MOUNTAIN', 'NOTEBOOK', 'OCTOPUS', 'PENGUIN', 'PUZZLE', 'RAINBOW', 'SUNFLOWER', 'TORTOISE',
  'WATERFALL', 'BUTTERFLY', 'CHOCOLATE', 'DRAGON', 'FEATHER', 'GIRAFFE', 'HONEY', 'ICECREAM',
  'KANGAROO', 'LIBRARY', 'MIRROR', 'NECTAR', 'PAINTBRUSH', 'QUEEN', 'SPIDER', 'TREASURE',
  'VOLCANO', 'WHISPER', 'BASKET', 'CLOCK', 'DIAMOND', 'EAGLE', 'FLOWER', 'GLASSES',
  'HORSE', 'IGUANA', 'JUICE', 'KOALA', 'LOCKET', 'MEADOW', 'NEEDLE', 'OATMEAL',
  'PEBBLE', 'QUIVER', 'RAISIN', 'SAILOR', 'THUNDER', 'UNICORN', 'VELVET', 'WINDMILL',
  'ABSTRACT', 'BOUNCY', 'CIRCUIT', 'DYNAMITE', 'ENVELOPE', 'FLAMINGO', 'GEYSER', 'HIKING',
  'JOURNAL', 'KETCHUP', 'LUNAR', 'MARBLE', 'NUCLEAR', 'ORCHID', 'PRISM', 'QUILT',
  'RECIPE', 'SATELLITE', 'TELESCOPE', 'URANIUM', 'VETERAN', 'WILDLIFE', 'XYLOPHONE', 'YOGURT',
  'ZEPHYR', 'AMBER', 'BERRY', 'CORAL', 'DAISY', 'EMBER', 'FROST', 'GLACIER',
  'HAVEN', 'IVORY', 'JASMINE', 'KNIGHT', 'LILY', 'MANGO', 'NORTH', 'OASIS',
  'PEARL', 'QUARTZ', 'RIBBON', 'SHELL', 'TOPAZ', 'URCHIN', 'VIOLET', 'WHARF',
];
