/**
 * Server-owned dictionary for Word Scramble Battle.
 *
 * The client never receives this list: the server picks a word per round and
 * only the scrambled letters are broadcast. The original word is revealed
 * after the round has ended.
 */
export const SCRAMBLE_WORDS: string[] = [
  // --- Original Words ---
  'PLANET', 'GARDEN', 'MARKET', 'SILVER', 'BRIDGE', 'CANDLE', 'DANGER', 'FRIEND',
  'GHOST', 'ISLAND', 'JUNGLE', 'KITTEN', 'LEMON', 'MAGIC', 'NOBLE', 'ORANGE',
  'PIANO', 'QUEST', 'RIVER', 'SINGER', 'TIGER', 'UNCLE', 'VIOLIN', 'WINTER',
  'YELLOW', 'ZEBRA', 'ANCHOR', 'BOTTLE', 'CASTLE', 'DINNER', 'ENGINE', 'FOREST',
  'GALAXY', 'HAMMER', 'IGLOO', 'JACKET', 'LADDER', 'MONKEY', 'NESTLE', 'OYSTER',
  'PARROT', 'QUARREL', 'ROCKET', 'SANDAL', 'TEMPLE', 'UMBRELLA', 'VULTURE', 'WALNUT',
  'BALLOON', 'COMPASS', 'DOLPHIN', 'ELEPHANT', 'FESTIVAL', 'GRAPES', 'HARBOUR', 'LANTERN',
  'MOUNTAIN', 'NOTEBOOK', 'OCTOPUS', 'PENGUIN', 'PUZZLE', 'RAINBOW', 'SUNFLOWER', 'TORTOISE',
  'WATERFALL', 'BUTTERFLY', 'CHOCOLATE', 'DRAGON', 'FEATHER', 'GIRAFFE', 'HONEY', 'ICECREAM',
  'KANGAROO', 'LIBRARY', 'MIRROR', 'NECTAR', 'PAINTBRUSH', 'QUEEN', 'SPIDER', 'TREASURE',
  'VOLCANO', 'WHISPER', 'BASKET', 'CLOCK', 'DIAMOND', 'EAGLE', 'FLOWER', 'GLASSES',
  'HORSE', 'IGUANA', 'JUICE', 'KOALA', 'LOCKET', 'MEADOW', 'NEEDLE', 'OATMEAL',
  'PEBBLE', 'QUIVER', 'RAISIN', 'SAILOR', 'THUNDER', 'UNICORN', 'VELVET', 'WINDMILL',
  'ABSTRACT', 'BOUNCY', 'CIRCUIT', 'DYNAMITE', 'ENVELOPE', 'FLAMINGO', 'GEYSER', 'HIKING',
  'JOURNAL', 'KETCHUP', 'LUNAR', 'MARBLE', 'NUCLEAR', 'ORCHID', 'PRISM', 'QUILT',
  'RECIPE', 'SATELLITE', 'TELESCOPE', 'URANIUM', 'VETERAN', 'WILDLIFE', 'XYLOPHONE', 'YOGURT',
  'ZEPHYR', 'AMBER', 'BERRY', 'CORAL', 'DAISY', 'EMBER', 'FROST', 'GLACIER',
  'HAVEN', 'IVORY', 'JASMINE', 'KNIGHT', 'LILY', 'MANGO', 'NORTH', 'OASIS',
  'PEARL', 'QUARTZ', 'RIBBON', 'SHELL', 'TOPAZ', 'URCHIN', 'VIOLET', 'WHARF',

  // --- Animals & Birds ---
  'DOG', 'CAT', 'LION', 'BEAR', 'WOLF', 'FOX', 'DEER', 'RABBIT', 'COW', 'SHEEP', 
  'GOAT', 'PIG', 'CAMEL', 'WHALE', 'SHARK', 'FISH', 'BIRD', 'OWL', 'PIGEON', 'CROW', 
  'DUCK', 'SWAN', 'FROG', 'SNAKE', 'TURTLE', 'LIZARD', 'ANT', 'BEE', 'MOUSE', 'RAT', 
  'SQUIRREL', 'BAT', 'PANDA', 'LEOPARD', 'CHEETAH', 'HIPPO', 'RHINO', 'BUFFALO', 'SEAL', 'WALRUS', 
  'CRAB', 'LOBSTER', 'SHRIMP', 'JELLYFISH', 'STARFISH', 'SNAIL', 'WORM', 'CATERPILLAR', 'LADYBUG', 'MOSQUITO', 
  'FLY', 'WASP', 'HORNET', 'MOTH', 'TURKEY', 'CHICKEN', 'ROOSTER', 'GOOSE', 'STORK', 'HERON', 
  'OSTRICH', 'PEACOCK', 'FALCON', 'HAWK', 'WOODPECKER', 'SPARROW', 'ROBIN', 'SWALLOW', 'CANARY', 'PELICAN', 
  'SEAGULL', 'OTTER', 'BEAVER', 'BADGER', 'RACCOON', 'SKUNK', 'HEDGEHOG', 'MOLE', 'HYENA', 'JACKAL', 
  'COYOTE', 'BISON', 'MOOSE', 'ELK', 'REINDEER', 'YAK', 'LLAMA', 'ALPACA', 'DONKEY', 'MULE', 'PONY',

  // --- Foods, Fruits & Vegetables ---
  'APPLE', 'BANANA', 'PAPAYA', 'GUAVA', 'PINEAPPLE', 'WATERMELON', 'MELON', 'PEACH', 'PLUM', 'CHERRY', 
  'STRAWBERRY', 'BLUEBERRY', 'BLACKBERRY', 'RASPBERRY', 'LIME', 'KIWI', 'FIG', 'DATE', 'APRICOT', 'POMEGRANATE', 
  'COCONUT', 'TOMATO', 'POTATO', 'ONION', 'GARLIC', 'GINGER', 'CARROT', 'RADISH', 'BEETROOT', 'CUCUMBER', 
  'CABBAGE', 'CAULIFLOWER', 'BROCCOLI', 'SPINACH', 'LETTUCE', 'PEAS', 'BEANS', 'LENTILS', 'RICE', 'WHEAT', 
  'BARLEY', 'OATS', 'CORN', 'FLOUR', 'BREAD', 'BUTTER', 'CHEESE', 'MILK', 'CURD', 'PANEER', 
  'CREAM', 'EGG', 'MEAT', 'MUTTON', 'PRAWN', 'SALT', 'SUGAR', 'PEPPER', 'OIL', 'GHEE', 
  'JAM', 'JELLY', 'SAUCE', 'VINEGAR', 'SOUP', 'NOODLES', 'PASTA', 'PIZZA', 'BURGER', 'SANDWICH', 
  'BISCUIT', 'COOKIE', 'CAKE', 'PASTRY', 'CANDY', 'TEA', 'COFFEE', 'SODA', 'WATER', 'WINE', 'BEER',

  // --- House & Household Objects ---
  'HOUSE', 'HOME', 'ROOM', 'DOOR', 'WINDOW', 'WALL', 'ROOF', 'FLOOR', 'CEILING', 'STAIRS', 
  'BALCONY', 'KITCHEN', 'BATHROOM', 'BEDROOM', 'HALL', 'GARAGE', 'GATE', 'FENCE', 'TABLE', 'CHAIR', 
  'BED', 'SOFA', 'CUSHION', 'PILLOW', 'BLANKET', 'SHEET', 'MATTRESS', 'ALMIRAH', 'CUPBOARD', 'DRAWER', 
  'SHELF', 'LAMP', 'BULB', 'FAN', 'HEATER', 'SCREEN', 'REMOTE', 'PHONE', 'LAPTOP', 'COMPUTER', 
  'TABLET', 'CAMERA', 'SPEAKER', 'RADIO', 'BUCKET', 'MUG', 'BOWL', 'PLATE', 'SPOON', 'FORK', 
  'KNIFE', 'CUP', 'POT', 'PAN', 'KETTLE', 'STOVE', 'OVEN', 'FRIDGE', 'MIXER', 'GRINDER', 
  'BROOM', 'MOP', 'SOAP', 'SHAMPOO', 'TOWEL', 'COMB', 'BRUSH', 'TOOTHPASTE', 'RAZOR', 'TISSUE', 
  'HANGER', 'LOCK', 'KEY', 'CHAIN', 'ROPE', 'CORD', 'PLUG', 'WIRE', 'SWITCH',

  // --- Nature & Weather ---
  'SKY', 'CLOUD', 'SNOW', 'WIND', 'STORM', 'LIGHTNING', 'FOG', 'MIST', 'DEW', 'HAIL', 
  'HEAT', 'COLD', 'WARM', 'COOL', 'WEATHER', 'CLIMATE', 'SEASON', 'SPRING', 'SUMMER', 'AUTUMN', 
  'MONSOON', 'EARTH', 'LAND', 'SOIL', 'DUST', 'MUD', 'STONE', 'HILL', 'VALLEY', 'DESERT', 
  'WOODS', 'TREE', 'PLANT', 'LEAF', 'BRANCH', 'STEM', 'ROOT', 'BUD', 'PETAL', 'GRASS', 
  'BUSH', 'SHRUB', 'STREAM', 'LAKE', 'POND', 'SEA', 'WAVE', 'TIDE', 'BEACH', 'COAST', 
  'PENINSULA', 'BAY', 'GULF', 'SPRING', 'WELL', 'FLOOD', 'DROUGHT', 'EARTHQUAKE', 'LAVA', 'ASH', 
  'FIRE', 'FLAME', 'SMOKE',

  // --- Colors ---
  'RED', 'BLUE', 'GREEN', 'PURPLE', 'PINK', 'BLACK', 'WHITE', 'BROWN', 'GREY', 'GOLD', 
  'BRONZE', 'INDIGO', 'MAROON', 'NAVY', 'TEAL', 'CYAN', 'MAGENTA', 'TURQUOISE', 'CRIMSON', 'OLIVE', 
  'BEIGE', 'CREAM', 'TAN', 'KHAKI',

  // --- Body Parts & Health ---
  'HEAD', 'HAIR', 'FACE', 'FOREHEAD', 'EYE', 'EYEBROW', 'EYELASH', 'EAR', 'NOSE', 'NOSTRIL', 
  'CHEEK', 'MOUTH', 'LIP', 'TOOTH', 'TONGUE', 'CHIN', 'JAW', 'NECK', 'THROAT', 'SHOULDER', 
  'ARM', 'ELBOW', 'FOREARM', 'WRIST', 'HAND', 'PALM', 'FINGER', 'THUMB', 'NAIL', 'CHEST', 
  'BREAST', 'STOMACH', 'BELLY', 'NAVEL', 'BACK', 'SPINE', 'WAIST', 'HIP', 'LEG', 'THIGH', 
  'KNEE', 'CALF', 'ANKLE', 'FOOT', 'HEEL', 'TOE', 'SKIN', 'BONE', 'SKULL', 'BLOOD', 
  'HEART', 'LUNGS', 'BRAIN', 'MUSCLE', 'NERVE', 'VEIN', 'HEALTH', 'SICK', 'ILL', 'PAIN', 
  'FEVER', 'COUGH', 'DOCTOR', 'NURSE', 'HOSPITAL', 'CLINIC', 'MEDICINE', 'PILL', 'SYRINGE', 'BANDAGE', 
  'WOUND', 'SCAR',

  // --- Clothing & Accessories ---
  'CLOTHES', 'SHIRT', 'TSHIRT', 'PANTS', 'JEANS', 'TROUSERS', 'SHORTS', 'SKIRT', 'DRESS', 'GOWN', 
  'SUIT', 'COAT', 'SWEATER', 'HOODIE', 'BLAZER', 'VEST', 'UNDERWEAR', 'SOCKS', 'SHOES', 'BOOTS', 
  'SANDALS', 'SLIPPERS', 'SNEAKERS', 'BELT', 'TIE', 'SCARF', 'SHAWL', 'GLOVES', 'CAP', 'HAT', 
  'TURBAN', 'HELMET', 'SUNGLASSES', 'RING', 'EARRING', 'NECKLACE', 'BRACELET', 'BANGLE', 'PURSE', 'WALLET', 
  'BAG', 'BACKPACK',

  // --- School, Office & Stationery ---
  'SCHOOL', 'COLLEGE', 'UNIVERSITY', 'CLASS', 'CLASSROOM', 'BENCH', 'DESK', 'BLACKBOARD', 'WHITEBOARD', 'CHALK', 
  'DUSTER', 'BOOK', 'PEN', 'PENCIL', 'ERASER', 'SHARPENER', 'Ruler', 'SCALE', 'PROTRACTOR', 'POUCH', 
  'FILE', 'FOLDER', 'PAPER', 'PAGE', 'NOTE', 'LETTER', 'STAMP', 'INK', 'MARKER', 'CRAYON', 
  'PAINT', 'MAP', 'GLOBE', 'ATLAS', 'DICTIONARY', 'CALCULATOR', 'PRINTER', 'SCANNER', 'OFFICE', 'MEETING', 
  'BOSS', 'MANAGER', 'EMPLOYEE', 'WORK', 'JOB', 'TASK', 'PROJECT', 'REPORT', 'EMAIL', 'MESSAGE', 
  'CALL', 'CABINET',

  // --- Family, People & Emotions ---
  'FAMILY', 'FATHER', 'MOTHER', 'PARENTS', 'SON', 'DAUGHTER', 'BROTHER', 'SISTER', 'HUSBAND', 'WIFE', 
  'GRANDFATHER', 'GRANDMOTHER', 'GRANDPA', 'GRANDMA', 'AUNT', 'COUSIN', 'NEPHEW', 'NIECE', 'ENEMY', 'NEIGHBOR', 
  'GUEST', 'HOST', 'MAN', 'WOMAN', 'BOY', 'GIRL', 'CHILD', 'BABY', 'TODDLER', 'ADULT', 
  'ELDER', 'PERSON', 'PEOPLE', 'CROWD', 'TEAM', 'PLAYER', 'LEADER', 'KING', 'PRINCE', 'PRINCESS', 
  'HERO', 'VILLAIN', 'MASTER', 'SERVANT', 'HAPPY', 'SAD', 'ANGRY', 'EXCITED', 'SCARED', 'AFRAID', 
  'NERVOUS', 'CALM', 'PEACEFUL', 'PROUD', 'JEALOUS', 'ENVIOUS', 'GRATEFUL', 'HOPEFUL', 'HOPELESS', 'BORED', 
  'TIRED', 'SLEEPY', 'HUNGRY', 'THIRSTY', 'SURPRISED', 'SHOCKED', 'CONFUSED', 'CURIOUS', 'BRAVE', 'COWARD', 
  'KIND', 'CRUEL', 'FRIENDLY', 'RUDE', 'POLITE', 'HONEST', 'LIAR', 'WISE', 'FOOLISH', 'SMART', 
  'DUMB', 'FUNNY', 'SERIOUS',

  // --- Professions & Occupations ---
  'TEACHER', 'PROFESSOR', 'STUDENT', 'SURGEON', 'DENTIST', 'LAWYER', 'JUDGE', 'POLICE', 'SOLDIER', 'OFFICER', 
  'GUARD', 'PILOT', 'DRIVER', 'CONDUCTOR', 'MECHANIC', 'ENGINEER', 'ARCHITECT', 'SCIENTIST', 'RESEARCHER', 'FARMER', 
  'COOK', 'CHEF', 'BAKER', 'WAITER', 'WAITRESS', 'BARBER', 'TAILOR', 'COBBLER', 'CARPENTER', 'MASON', 
  'PLUMBER', 'ELECTRICIAN', 'PAINTER', 'CLEANER', 'SWEEPER', 'DANCER', 'ACTOR', 'ACTRESS', 'MUSICIAN', 'ARTIST', 
  'WRITER', 'POET', 'AUTHOR', 'JOURNALIST', 'REPORTER', 'PHOTOGRAPHER', 'CAMERAMAN', 'ATHLETE', 'COACH', 'REFEREE', 
  'BUSINESSMAN', 'TRADER', 'SHOPKEEPER', 'BANKER', 'CASHIER', 'ACCOUNTANT', 'SECRETARY',

  // --- Time, Calendar & Numbers ---
  'TIME', 'HOUR', 'MINUTE', 'SECOND', 'MOMENT', 'DAY', 'NIGHT', 'MORNING', 'AFTERNOON', 'EVENING', 
  'MIDNIGHT', 'WEEK', 'MONTH', 'YEAR', 'DECADE', 'CENTURY', 'PAST', 'PRESENT', 'FUTURE', 'TODAY', 
  'YESTERDAY', 'TOMORROW', 'ALWAYS', 'NEVER', 'OFTEN', 'SOMETIMES', 'SOON', 'LATER', 'EARLY', 'LATE', 
  'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', 'JANUARY', 'FEBRUARY', 'MARCH', 
  'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', 'ZERO', 
  'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN', 
  'ELEVEN', 'TWELVE', 'THIRTEEN', 'FOURTEEN', 'FIFTEEN', 'SIXTEEN', 'SEVENTEEN', 'EIGHTEEN', 'NINETEEN', 'TWENTY', 
  'THIRTY', 'FORTY', 'FIFTY', 'SIXTY', 'SEVENTY', 'EIGHTY', 'NINETY', 'HUNDRED', 'THOUSAND', 'LAKH', 
  'CRORE', 'MILLION', 'BILLION', 'FIRST', 'THIRD', 'LAST', 'HALF', 'QUARTER', 'DOUBLE', 'TRIPLE',

  // --- Places & Buildings ---
  'PLACE', 'CITY', 'TOWN', 'VILLAGE', 'STATE', 'COUNTRY', 'CONTINENT', 'WORLD', 'CAPITAL', 'STREET', 
  'ROAD', 'LANE', 'AVENUE', 'HIGHWAY', 'TUNNEL', 'SQUARE', 'SHOP', 'STORE', 'MALL', 'HOTEL', 
  'RESTAURANT', 'CAFE', 'CINEMA', 'THEATRE', 'PARK', 'ZOO', 'MUSEUM', 'PHARMACY', 'BANK', 'POSTOFFICE', 
  'STATION', 'AIRPORT', 'PORT', 'HARBOR', 'MOSQUE', 'CHURCH', 'GURUDWARA', 'PALACE', 'FORT', 'TOWER', 
  'BUILDING', 'APARTMENT', 'HUT', 'TENT',

  // --- Actions & Verbs ---
  'GO', 'COME', 'RUN', 'WALK', 'JUMP', 'SIT', 'STAND', 'SLEEP', 'WAKE', 'EAT', 
  'DRINK', 'WASH', 'CLEAN', 'SWEEP', 'PLAY', 'READ', 'WRITE', 'SPEAK', 'TALK', 'LISTEN', 
  'HEAR', 'SEE', 'LOOK', 'WATCH', 'THINK', 'KNOW', 'LEARN', 'TEACH', 'STUDY', 'UNDERSTAND', 
  'REMEMBER', 'FORGET', 'BUY', 'SELL', 'PAY', 'COST', 'GIVE', 'TAKE', 'BRING', 'SEND', 
  'RECEIVE', 'OPEN', 'CLOSE', 'UNLOCK', 'START', 'STOP', 'BEGIN', 'END', 'WIN', 'LOSE', 
  'FIGHT', 'MATCH', 'RACE', 'FLY', 'SWIM', 'DIVE', 'RIDE', 'SAIL', 'FALL', 'RISE', 
  'GROW', 'CUT', 'BREAK', 'FIX', 'REPAIR', 'BUILD', 'MAKE', 'CREATE', 'DRAW', 'SING', 
  'SMILE', 'LAUGH', 'CRY', 'WEEP', 'SHOUT', 'TOUCH', 'FEEL', 'SMELL', 'TASTE', 'PUSH', 
  'PULL', 'CARRY', 'HOLD', 'DROP', 'THROW', 'CATCH', 'HIDE', 'SEEK', 'FIND', 'SEARCH', 
  'CHASE', 'ESCAPE', 'SAVE', 'PROTECT', 'ATTACK', 'KILL', 'DIE', 'LIVE', 'BORN', 'CHANGE', 
  'MOVE', 'TURN', 'STAY', 'WAIT', 'HELD', 'KEEP',

  // --- Adjectives & Descriptors ---
  'GOOD', 'BAD', 'BETTER', 'BEST', 'WORSE', 'WORST', 'BIG', 'SMALL', 'LARGE', 'LITTLE', 
  'TALL', 'SHORT', 'HIGH', 'LOW', 'LONG', 'WIDE', 'NARROW', 'THICK', 'THIN', 'FAT', 
  'SLIM', 'HEAVY', 'FAST', 'SLOW', 'QUICK', 'HARD', 'SOFT', 'SMOOTH', 'ROUGH', 'WET', 
  'DRY', 'CLEAN', 'DIRTY', 'NEW', 'OLD', 'YOUNG', 'ANCIENT', 'MODERN', 'FRESH', 'ROTTEN', 
  'SWEET', 'SOUR', 'BITTER', 'SALTY', 'SPICY', 'TASTY', 'DELICIOUS', 'BRIGHT', 'SHINY', 'DULL', 
  'LOUD', 'QUIET', 'SILENT', 'NOISY', 'RICH', 'POOR', 'CHEAP', 'EXPENSIVE', 'FREE', 'FULL', 
  'EMPTY', 'TRUE', 'FALSE', 'RIGHT', 'WRONG', 'CORRECT', 'INCORRECT', 'EASY', 'DIFFICULT', 'SIMPLE', 
  'COMPLEX', 'SAFE', 'DANGEROUS', 'NEAT', 'MESSY', 'GLAD', 'MAD', 'WISE', 'CLEAN', 'STUPID', 
  'STRONG', 'WEAK', 'HEALTHY', 'HONEST', 'DISHONEST', 'BEAUTIFUL', 'UGLY', 'PRETTY', 'HANDSOME', 'CUTE', 
  'NICE', 'LOVELY', 'AWESOME', 'WONDERFUL', 'TERRIBLE', 'HORRIBLE', 'GREAT', 'FANTASTIC', 'EXCELLENT',

  // --- Transport, Travel & Space ---
  'CAR', 'BUS', 'TRUCK', 'VAN', 'BIKE', 'CYCLE', 'MOTORCYCLE', 'SCOOTER', 'AUTO', 'RICKSHAW', 
  'TRACTOR', 'TRAIN', 'METRO', 'TRAM', 'SHIP', 'BOAT', 'FERRY', 'YACHT', 'CRUISE', 'PLANE', 
  'AEROPLANE', 'HELICOPTER', 'SPACESHIP', 'TICKET', 'PLATFORM', 'TRACK', 'TRAFFIC', 'SIGNAL', 'PASSENGER', 'LUGGAGE', 
  'JOURNEY', 'TRIP', 'TOUR', 'VOYAGE', 'FLIGHT', 'TRAVEL', 'EXPLORE', 'ADVENTURE', 'GUIDE', 'TOURIST', 
  'RESORT', 'CAMP', 'PASSPORT', 'VISA', 'BOARD', 'ARRIVE', 'DEPART', 'DELAY', 'ONTIME',

  // --- Technology, Science & Miscellaneous ---
  'SMARTPHONE', 'DISPLAY', 'KEYBOARD', 'CHARGER', 'BATTERY', 'WIFI', 'INTERNET', 'NETWORK', 'WEBSITE', 'LINK', 
  'BROWSER', 'DATA', 'PROGRAM', 'CODE', 'SOFTWARE', 'HARDWARE', 'APP', 'VIDEO', 'AUDIO', 'MUSIC', 
  'SONG', 'PHOTO', 'PICTURE', 'FLASH', 'POWER', 'ENERGY', 'ELECTRICITY', 'SOCKET', 'MACHINE', 'TOOL', 
  'SCREWDRIVER', 'PLIERS', 'NAIL', 'SCREW', 'DRILL', 'SAW', 'BOX', 'CARTON', 'SACK', 'BARREL', 
  'TANK', 'PIPE', 'TUBE', 'VALVE', 'PUMP', 'WHEEL', 'GEAR', 'SPRING', 'MAGNET', 'LENS', 
  'TAPE', 'GLUE', 'SCISSORS', 'THREAD', 'BUTTON', 'ZIPPER'
];
