import { useCallback, useEffect, useRef, type ComponentType } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Circle } from 'lucide-react';
import { BLACK_BLAST_METADATA, type GameAction } from '@2play/shared';
import type { ClientGameModule, GameComponentProps } from '../registry/types';
import { GameHUD } from '../../components/game/GameHUD';
import { Badge } from '../../components/ui/Badge';
import { cn } from '../../utils/cn';
interface State { phase: 'idle'|'playing'|'finished'; width: number; height: number; players: Record<string, { x:number; y:number; score:number; combo:number; lastBlastAt:number; color:string }>; objects: { id:number; x:number; y:number; value:number }[]; blasts:{ id:number; ownerId:string; x:number; y:number; radius:number; expiresAt:number }[]; endsAt:number|null; lastEvent:string|null; winnerId:string|null; }
const DPad = [{ d: [0,-1], I: ArrowUp }, { d: [-1,0], I: ArrowLeft }, { d: [0,1], I: ArrowDown }, { d: [1,0], I: ArrowRight }];
function BlackBlast({ state, players, myPlayerId, sendAction, play, vibrate }: GameComponentProps<State>) {
 const canvas = useRef<HTMLCanvasElement | null>(null); const me = myPlayerId ? state.players[myPlayerId] : undefined;
 useEffect(() => { const el = canvas.current; if (!el) return; const rect = el.getBoundingClientRect(); const dpr = window.devicePixelRatio || 1; el.width = rect.width*dpr; el.height = rect.height*dpr; const ctx=el.getContext('2d'); if(!ctx) return; ctx.scale(dpr,dpr); ctx.clearRect(0,0,rect.width,rect.height); const sx=rect.width/100, sy=rect.height/100; ctx.fillStyle='#07111f'; ctx.fillRect(0,0,rect.width,rect.height); for(const o of state.objects){ctx.fillStyle='#a78bfa';ctx.beginPath();ctx.arc(o.x*sx,o.y*sy,5,0,Math.PI*2);ctx.fill();} for(const b of state.blasts){ctx.strokeStyle='#020617';ctx.lineWidth=5;ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(b.x*sx,b.y*sy,b.radius*sx,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;} players.forEach((player,index)=>{const p=state.players[player.id];if(!p)return;ctx.fillStyle=p.color||['#f87171','#60a5fa','#4ade80','#facc15'][index%4];ctx.beginPath();ctx.arc(p.x*sx,p.y*sy, index===0?7:6,0,Math.PI*2);ctx.fill();}); }, [state, players]);
 const sendMove = useCallback((dx:number,dy:number)=>{sendAction({type:'move',payload:{dx,dy}} satisfies GameAction); vibrate('buttonPress');},[sendAction,vibrate]);
 return <div className="space-y-4"><GameHUD players={players.map(p=>({...p,score:state.players[p.id]?.score??p.score}))} myPlayerId={myPlayerId} deadline={state.endsAt} label="Arena timer"/><div className="flex gap-2"><Badge tone="accent">Score {me?.score??0}</Badge><Badge tone="warning">Combo x{me?.combo??0}</Badge></div><div className="relative mx-auto aspect-square w-full max-w-lg overflow-hidden rounded-2xl border border-white/10"><canvas ref={canvas} className="h-full w-full" aria-label="Black Blast arena" />{state.lastEvent?.startsWith('chain:')&&<div className="pointer-events-none absolute inset-x-0 top-3 text-center text-sm font-bold text-violet-200">CHAIN REACTION!</div>}</div><div className="flex items-center justify-center gap-3"><div className="grid w-36 grid-cols-3 gap-2">{DPad.map(({d,I},i)=><button key={i} type="button" aria-label="Move" onClick={()=>sendMove(d[0],d[1])} className={cn('grid h-11 place-items-center rounded-lg border border-white/10 bg-white/5 active:scale-95',i===0?'col-start-2':i===1?'col-start-1':'') }><I className="h-5 w-5"/></button>)}</div><button type="button" aria-label="Trigger blast" disabled={!me||state.phase!=='playing'} onClick={()=>{sendAction({type:'blast'});play('score');vibrate('success')}} className="grid h-16 w-16 place-items-center rounded-full bg-slate-950 text-white shadow-[0_0_24px_rgba(15,23,42,.9)] active:scale-95"><Circle className="h-8 w-8"/></button></div><p className="text-center text-xs text-slate-500">Move into violet energy targets, then trigger an abstract black energy pulse. Chain reactions multiply your score.</p></div>;
}
export const blackBlastClient: ClientGameModule = { metadata: BLACK_BLAST_METADATA, Component: BlackBlast as unknown as ComponentType<GameComponentProps<never>> };
